#!/bin/sh

echo "/* don't edit, auto generated by build/tools/gencsiconfig.sh */"
echo "#ifndef __CSI_CONFIG_H__"
echo "#define __CSI_CONFIG_H__"

#define
cat $1/.config | sed 's/[[:space:]]//g' | grep "^[A-Z]" | grep -v "=n$" | sed 's/=y/ 1/' | sed 's/=/ /' | sed 's/^/#define /g'
# sed 's/\"/\\\"/g' | xargs -i echo -e "#define {}\n"

#undef
cat $1/.config | sed 's/[[:space:]]//g' | grep "^[A-Z]" | grep "=n$" | sed 's/=n//' | sed 's/^/#undef /g'
#xargs -i echo "#undef {}"

echo "#endif"
