//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef PMU_REG_OFFSET_DEFINE_H
#define PMU_REG_OFFSET_DEFINE_H

#define AON_PMU_REG_BASE	0xFFF42000

#define AON_PMU_PMU_CFG                 (AON_PMU_REG_BASE + 0x0 )
#define AON_PMU_GPIO_INT_MASK_CFG       (AON_PMU_REG_BASE + 0x10)
#define AON_PMU_INTC_INT_MASK_CFG_L     (AON_PMU_REG_BASE + 0x14)
#define AON_PMU_INTC_INT_MASK_CFG_H     (AON_PMU_REG_BASE + 0x18)
#define AON_PMU_GPIO_INT_POLARITY_CFG   (AON_PMU_REG_BASE + 0x20)
#define AON_PMU_PMU_INT_CLR_CFG         (AON_PMU_REG_BASE + 0x28)
#define AON_PMU_GPIO_INT_STS            (AON_PMU_REG_BASE + 0x30)
#define AON_PMU_INTC_INT_STS_L          (AON_PMU_REG_BASE + 0x34)
#define AON_PMU_INTC_INT_STS_H          (AON_PMU_REG_BASE + 0x38)
#define AON_PMU_PMU_STATUS_L            (AON_PMU_REG_BASE + 0x40)
#define AON_PMU_PMU_STATUS_H            (AON_PMU_REG_BASE + 0x44)
#define AON_PMU_WAIT_CNT                (AON_PMU_REG_BASE + 0x50)
#define AON_PMU_PD_CPU_SW_CNT           (AON_PMU_REG_BASE + 0x54)
#define AON_PMU_PD_CPU_INTV_CNT         (AON_PMU_REG_BASE + 0x58)
#define AON_PMU_PD_SW_POLARITY          (AON_PMU_REG_BASE + 0x5c)
#define AON_PMU_PMU_RESERVED_REG_0      (AON_PMU_REG_BASE + 0x60)
#define AON_PMU_PMU_RESERVED_REG_1      (AON_PMU_REG_BASE + 0x64)
#define AON_PMU_PMU_RESERVED_REG_3      (AON_PMU_REG_BASE + 0x6c)

#define PMU_CFG_DFLT_VAL                  0x5000
#define GPIO_INT_MASK_CFG_DFLT_VAL        0xffff
#define INTC_INT_MASK_CFG_L_DFLT_VAL      0xffffffff
#define INTC_INT_MASK_CFG_H_DFLT_VAL      0xffffffff
#define GPIO_INT_POLARITY_CFG_DFLT_VAL    0xffff
#define PMU_INT_CLR_CFG_DFLT_VAL          0x0
#define GPIO_INT_STS_DFLT_VAL             0x0
#define INTC_INT_STS_L_DFLT_VAL           0x0
#define INTC_INT_STS_H_DFLT_VAL           0x0
#define PMU_STATUS_L_DFLT_VAL             0x30
#define PMU_STATUS_H_DFLT_VAL             0x1
#define WAIT_CNT_DFLT_VAL                 0x108c6467
#define PD_CPU_SW_CNT_DFLT_VAL            0xffff
#define PD_CPU_INTV_CNT_DFLT_VAL          0xffffff
#define PD_SW_POLARITY_DFLT_VAL           0x0
#define PMU_RESERVED_REG_0_DFLT_VAL       0x0
#define PMU_RESERVED_REG_1_DFLT_VAL       0x0
#define PMU_RESERVED_REG_3_DFLT_VAL       0x0


#endif
