//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef AONSYS_CLKGEN_REG_SW_H
#define AONSYS_CLKGEN_REG_SW_H

typedef union {
    struct {
        unsigned int audio_pll_refdiv : 6; // [5:0]
        unsigned int RESERVED_2 : 2; // [7:6]
        unsigned int audio_pll_fbdiv : 12; // [19:8]
        unsigned int audio_pll_postdiv1 : 3; // [22:20]
        unsigned int RESERVED_1 : 1; // [23]
        unsigned int audio_pll_postdiv2 : 3; // [26:24]
        unsigned int RESERVED_0 : 5; // [31:27]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AUDIO_PLL_CFG0_U;

typedef union {
    struct {
        unsigned int audio_pll_frac : 24; // [23:0]
        unsigned int audio_pll_dsmpd : 1; // [24]
        unsigned int audio_pll_dacpd : 1; // [25]
        unsigned int RESERVED_1 : 1; // [26]
        unsigned int audio_pll_fout4phasepd : 1; // [27]
        unsigned int audio_pll_foutpostdivpd : 1; // [28]
        unsigned int audio_pll_rst : 1; // [29]
        unsigned int audio_pll_bypass : 1; // [30]
        unsigned int RESERVED_0 : 1; // [31]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AUDIO_PLL_CFG1_U;

typedef union {
    struct {
        unsigned int audio_pll_dskewcalout : 12; // [11:0]
        unsigned int audio_pll_dskewcalin : 12; // [23:12]
        unsigned int audio_pll_dskewcalcnt : 3; // [26:24]
        unsigned int audio_pll_dskewfastcal : 1; // [27]
        unsigned int audio_pll_dskewcalen : 1; // [28]
        unsigned int audio_pll_dskewcalbyp : 1; // [29]
        unsigned int audio_pll_dskewcallock : 1; // [30]
        unsigned int RESERVED_0 : 1; // [31]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AUDIO_PLL_CFG2_U;

typedef union {
    struct {
        unsigned int audio_pll_dskewcal_stat : 4; // [3:0]
        unsigned int RESERVED_1 : 3; // [6:4]
        unsigned int audio_pll_dskewcal_rdy : 1; // [7]
        unsigned int audio_pll_dskewcal_sw_en : 1; // [8]
        unsigned int audio_pll_dskewcal_pulse : 1; // [9]
        unsigned int audio_pll_callock_cnt_en : 1; // [10]
        unsigned int RESERVED_0 : 1; // [11]
        unsigned int audio_pll_callock_cnt : 20; // [31:12]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AUDIO_PLL_CFG3_U;

typedef union {
    struct {
        unsigned int sys_pll_refdiv : 6; // [5:0]
        unsigned int RESERVED_2 : 2; // [7:6]
        unsigned int sys_pll_fbdiv : 12; // [19:8]
        unsigned int sys_pll_postdiv1 : 3; // [22:20]
        unsigned int RESERVED_1 : 1; // [23]
        unsigned int sys_pll_postdiv2 : 3; // [26:24]
        unsigned int RESERVED_0 : 5; // [31:27]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_SYS_PLL_CFG0_U;

typedef union {
    struct {
        unsigned int sys_pll_frac : 24; // [23:0]
        unsigned int sys_pll_dsmpd : 1; // [24]
        unsigned int sys_pll_dacpd : 1; // [25]
        unsigned int RESERVED_1 : 1; // [26]
        unsigned int sys_pll_fout4phasepd : 1; // [27]
        unsigned int sys_pll_foutpostdivpd : 1; // [28]
        unsigned int sys_pll_rst : 1; // [29]
        unsigned int sys_pll_bypass : 1; // [30]
        unsigned int RESERVED_0 : 1; // [31]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_SYS_PLL_CFG1_U;

typedef union {
    struct {
        unsigned int sys_pll_dskewcalout : 12; // [11:0]
        unsigned int sys_pll_dskewcalin : 12; // [23:12]
        unsigned int sys_pll_dskewcalcnt : 3; // [26:24]
        unsigned int sys_pll_dskewfastcal : 1; // [27]
        unsigned int sys_pll_dskewcalen : 1; // [28]
        unsigned int sys_pll_dskewcalbyp : 1; // [29]
        unsigned int sys_pll_dskewcallock : 1; // [30]
        unsigned int RESERVED_0 : 1; // [31]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_SYS_PLL_CFG2_U;

typedef union {
    struct {
        unsigned int sys_pll_dskewcal_stat : 4; // [3:0]
        unsigned int RESERVED_1 : 3; // [6:4]
        unsigned int sys_pll_dskewcal_rdy : 1; // [7]
        unsigned int sys_pll_dskewcal_sw_en : 1; // [8]
        unsigned int sys_pll_dskewcal_pulse : 1; // [9]
        unsigned int sys_pll_callock_cnt_en : 1; // [10]
        unsigned int RESERVED_0 : 1; // [11]
        unsigned int sys_pll_callock_cnt : 20; // [31:12]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_SYS_PLL_CFG3_U;

typedef union {
    struct {
        unsigned int audio_pll_lock : 1; // [0]
        unsigned int sys_pll_lock : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AONSYS_PLL_STS_U;

typedef union {
    struct {
        unsigned int aonsys_clk_cde_ratio : 3; // [2:0]
        unsigned int aonsys_clk_cde_sync : 1; // [3]
        unsigned int aonsys_clk_switch_0_switch_sel : 1; // [4]
        unsigned int aonsys_clk_switch_1_switch_sel : 1; // [5]
        unsigned int RESERVED_1 : 2; // [7:6]
        unsigned int aonsys_clk_pll_src_div_num : 3; // [10:8]
        unsigned int aonsys_clk_pll_src_div_en : 1; // [11]
        unsigned int RESERVED_0 : 20; // [31:12]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AONSYS_CLK_CFG_U;

typedef union {
    struct {
        unsigned int share_sram_clk_div_0_div_num : 4; // [3:0]
        unsigned int share_sram_clk_div_0_div_en : 1; // [4]
        unsigned int RESERVED_1 : 3; // [7:5]
        unsigned int share_sram_clk_div_1_div_num : 4; // [11:8]
        unsigned int share_sram_clk_div_1_div_en : 1; // [12]
        unsigned int share_sram_clk_switch_sel : 1; // [13]
        unsigned int RESERVED_0 : 18; // [31:14]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_SHARE_SRAM_CLK_CFG_U;

typedef union {
    struct {
        unsigned int audio_subsys_aclk_div_0_div_num : 4; // [3:0]
        unsigned int audio_subsys_aclk_div_0_div_en : 1; // [4]
        unsigned int RESERVED_1 : 3; // [7:5]
        unsigned int audio_subsys_aclk_div_1_div_num : 4; // [11:8]
        unsigned int audio_subsys_aclk_div_1_div_en : 1; // [12]
        unsigned int audio_subsys_aclk_switch_sel : 1; // [13]
        unsigned int RESERVED_0 : 18; // [31:14]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AUDIO_SUBSYS_ACLK_CFG_U;

typedef union {
    struct {
        unsigned int audio_i2s_src_clk_switch_sel : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AUDIO_I2S_CLK_CFG_U;

typedef union {
    struct {
        unsigned int audio_c906_cclk_div_0_div_num : 4; // [3:0]
        unsigned int audio_c906_cclk_div_0_div_en : 1; // [4]
        unsigned int RESERVED_1 : 3; // [7:5]
        unsigned int audio_c906_cclk_div_1_div_num : 4; // [11:8]
        unsigned int audio_c906_cclk_div_1_div_en : 1; // [12]
        unsigned int audio_c906_cclk_switch_sel : 1; // [13]
        unsigned int RESERVED_0 : 18; // [31:14]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AUDIO_C906_CCLK_CFG_U;

typedef union {
    struct {
        unsigned int audio_subsys_aclk_cp2ap_en : 1; // [0]
        unsigned int audio_subsys_aclk_ap2cp_en : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AUDIO_CLK_GATE_U;

typedef union {
    struct {
        unsigned int aoi2c_ic_clk_mux_sel : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AOI2C_CLK_CFG_U;

typedef union {
    struct {
        unsigned int rtc_pclk_en : 1; // [0]
        unsigned int sram_axi_core_clk_en : 1; // [1]
        unsigned int sram_axi_aclk_4_en : 1; // [2]
        unsigned int pvtc_pclk_en : 1; // [3]
        unsigned int aopad_pclk_en : 1; // [4]
        unsigned int RESERVED_3 : 1; // [5]
        unsigned int aosram_hclk_en : 1; // [6]
        unsigned int RESERVED_2 : 1; // [7]
        unsigned int aogpio_pclk_en : 1; // [8]
        unsigned int aogpio_dbclk_en : 1; // [9]
        unsigned int aotimer_pclk_en : 1; // [10]
        unsigned int aotimer_cclk_en : 1; // [11]
        unsigned int RESERVED_1 : 1; // [12]
        unsigned int aowdt_pclk_en : 1; // [13]
        unsigned int dspsys_aclk_s_en : 1; // [14]
        unsigned int adc_pclk_en : 1; // [15]
        unsigned int audgpio_pclk_en : 1; // [16]
        unsigned int audgpio_dbclk_en : 1; // [17]
        unsigned int aoi2c_ic_clk_en : 1; // [18]
        unsigned int aoi2c_pclk_en : 1; // [19]
        unsigned int aouart_sclk_en : 1; // [20]
        unsigned int aouart_pclk_en : 1; // [21]
        unsigned int RESERVED_0 : 10; // [31:22]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AONSYS_CLK_GATE_U;

typedef union {
    struct {
        unsigned int apsys_clk_en : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_APSYS_CLK_GATE_U;

typedef union {
    struct {
        unsigned int dsp0_clk_en : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_DSP0_CLK_GATE_U;

typedef union {
    struct {
        unsigned int dsp1_clk_en : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_DSP1_CLK_GATE_U;

typedef union {
    struct {
        unsigned int gpu_clk_en : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_GPU_CLK_GATE_U;

typedef union {
    struct {
        unsigned int vdec_clk_en : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_VDEC_CLK_GATE_U;

typedef union {
    struct {
        unsigned int venc_clk_en : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_VENC_CLK_GATE_U;

typedef union {
    struct {
        unsigned int reserved_reg_0 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_RESERVED_REG_0_U;

typedef union {
    struct {
        unsigned int reserved_reg_1 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_RESERVED_REG_1_U;

typedef union {
    struct {
        unsigned int reserved_reg_2 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_RESERVED_REG_2_U;

typedef union {
    struct {
        unsigned int reserved_reg_3 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_RESERVED_REG_3_U;

typedef union {
    struct {
        unsigned int aonsys_clk_mntedclk_divfactor : 10; // [9:0]
        unsigned int aonsys_clk_mnt_thl : 10; // [19:10]
        unsigned int aonsys_clk_mnt_thh : 10; // [29:20]
        unsigned int aonsys_clk_mnt_en : 1; // [30]
        unsigned int aonsys_clk_mnt_cfg_lock : 1; // [31]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_AONSYS_CLK_MNT_TEECFG_U;

typedef union {
    struct {
        unsigned int test_clk_sel : 4; // [3:0]
        unsigned int test_clk_sample_en : 1; // [4]
        unsigned int RESERVED_0 : 27; // [31:5]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_TEST_CLK_CFG_U;

typedef union {
    struct {
        unsigned int test_clk_freq_stat : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_CLKGEN_REG_SW_TEST_CLK_STS_U;

typedef union {
    volatile AONSYS_CLKGEN_REG_SW_AUDIO_PLL_CFG0_U aonsys_clkgen_reg_sw_audio_pll_cfg0;    // 0x0
    volatile AONSYS_CLKGEN_REG_SW_AUDIO_PLL_CFG1_U aonsys_clkgen_reg_sw_audio_pll_cfg1;    // 0x4
    volatile AONSYS_CLKGEN_REG_SW_AUDIO_PLL_CFG2_U aonsys_clkgen_reg_sw_audio_pll_cfg2;    // 0x8
    volatile AONSYS_CLKGEN_REG_SW_AUDIO_PLL_CFG3_U aonsys_clkgen_reg_sw_audio_pll_cfg3;    // 0xc
    volatile AONSYS_CLKGEN_REG_SW_SYS_PLL_CFG0_U aonsys_clkgen_reg_sw_sys_pll_cfg0;    // 0x10
    volatile AONSYS_CLKGEN_REG_SW_SYS_PLL_CFG1_U aonsys_clkgen_reg_sw_sys_pll_cfg1;    // 0x14
    volatile AONSYS_CLKGEN_REG_SW_SYS_PLL_CFG2_U aonsys_clkgen_reg_sw_sys_pll_cfg2;    // 0x18
    volatile AONSYS_CLKGEN_REG_SW_SYS_PLL_CFG3_U aonsys_clkgen_reg_sw_sys_pll_cfg3;    // 0x1c
    volatile AONSYS_CLKGEN_REG_SW_AONSYS_PLL_STS_U aonsys_clkgen_reg_sw_aonsys_pll_sts;    // 0x90
    volatile AONSYS_CLKGEN_REG_SW_AONSYS_CLK_CFG_U aonsys_clkgen_reg_sw_aonsys_clk_cfg;    // 0x100
    volatile AONSYS_CLKGEN_REG_SW_SHARE_SRAM_CLK_CFG_U aonsys_clkgen_reg_sw_share_sram_clk_cfg;    // 0x104
    volatile AONSYS_CLKGEN_REG_SW_AUDIO_SUBSYS_ACLK_CFG_U aonsys_clkgen_reg_sw_audio_subsys_aclk_cfg;    // 0x108
    volatile AONSYS_CLKGEN_REG_SW_AUDIO_I2S_CLK_CFG_U aonsys_clkgen_reg_sw_audio_i2s_clk_cfg;    // 0x10c
    volatile AONSYS_CLKGEN_REG_SW_AUDIO_C906_CCLK_CFG_U aonsys_clkgen_reg_sw_audio_c906_cclk_cfg;    // 0x110
    volatile AONSYS_CLKGEN_REG_SW_AUDIO_CLK_GATE_U aonsys_clkgen_reg_sw_audio_clk_gate;    // 0x114
    volatile AONSYS_CLKGEN_REG_SW_AOI2C_CLK_CFG_U aonsys_clkgen_reg_sw_aoi2c_clk_cfg;    // 0x11c
    volatile AONSYS_CLKGEN_REG_SW_AONSYS_CLK_GATE_U aonsys_clkgen_reg_sw_aonsys_clk_gate;    // 0x120
    volatile AONSYS_CLKGEN_REG_SW_APSYS_CLK_GATE_U aonsys_clkgen_reg_sw_apsys_clk_gate;    // 0x130
    volatile AONSYS_CLKGEN_REG_SW_DSP0_CLK_GATE_U aonsys_clkgen_reg_sw_dsp0_clk_gate;    // 0x134
    volatile AONSYS_CLKGEN_REG_SW_DSP1_CLK_GATE_U aonsys_clkgen_reg_sw_dsp1_clk_gate;    // 0x138
    volatile AONSYS_CLKGEN_REG_SW_GPU_CLK_GATE_U aonsys_clkgen_reg_sw_gpu_clk_gate;    // 0x13c
    volatile AONSYS_CLKGEN_REG_SW_VDEC_CLK_GATE_U aonsys_clkgen_reg_sw_vdec_clk_gate;    // 0x140
    volatile AONSYS_CLKGEN_REG_SW_VENC_CLK_GATE_U aonsys_clkgen_reg_sw_venc_clk_gate;    // 0x144
    volatile AONSYS_CLKGEN_REG_SW_RESERVED_REG_0_U aonsys_clkgen_reg_sw_reserved_reg_0;    // 0x160
    volatile AONSYS_CLKGEN_REG_SW_RESERVED_REG_1_U aonsys_clkgen_reg_sw_reserved_reg_1;    // 0x164
    volatile AONSYS_CLKGEN_REG_SW_RESERVED_REG_2_U aonsys_clkgen_reg_sw_reserved_reg_2;    // 0x168
    volatile AONSYS_CLKGEN_REG_SW_RESERVED_REG_3_U aonsys_clkgen_reg_sw_reserved_reg_3;    // 0x16c
    volatile AONSYS_CLKGEN_REG_SW_AONSYS_CLK_MNT_TEECFG_U aonsys_clkgen_reg_sw_aonsys_clk_mnt_teecfg;    // 0x170
    volatile AONSYS_CLKGEN_REG_SW_TEST_CLK_CFG_U aonsys_clkgen_reg_sw_test_clk_cfg;    // 0x180
    volatile AONSYS_CLKGEN_REG_SW_TEST_CLK_STS_U aonsys_clkgen_reg_sw_test_clk_sts;    // 0x184
} AONSYS_CLKGEN_REG_SW_REG_S;

#endif
