//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef AONSYS_SYSREG_REG_SW_H
#define AONSYS_SYSREG_REG_SW_H

typedef union {
    struct {
        unsigned int c910_core0_lpmd_b : 2; // [1:0]
        unsigned int c910_core1_lpmd_b : 2; // [3:2]
        unsigned int c910_core2_lpmd_b : 2; // [5:4]
        unsigned int c910_core3_lpmd_b : 2; // [7:6]
        unsigned int c906_core_lpmd_b : 2; // [9:8]
        unsigned int RESERVED_0 : 22; // [31:10]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_CPU_LP_MODE_U;

typedef union {
    struct {
        unsigned int chip_lp_mode : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_CHIP_LP_MODE_U;

typedef union {
    struct {
        unsigned int ao_seram_trn : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_AO_SERAM_TRN_U;

typedef union {
    struct {
        unsigned int ao_sram_init : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_AO_SERAM_INT_U;

typedef union {
    struct {
        unsigned int str_seram_trn : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_STR_SERAM_TRN_U;

typedef union {
    struct {
        unsigned int str_sram_init : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_STR_SERAM_INT_U;

typedef union {
    struct {
        unsigned int str_indicator_0 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_STR_INDICATOR_0_U;

typedef union {
    struct {
        unsigned int str_indicator_1 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_STR_INDICATOR_1_U;

typedef union {
    struct {
        unsigned int str_indicator_2 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_STR_INDICATOR_2_U;

typedef union {
    struct {
        unsigned int str_indicator_3 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_STR_INDICATOR_3_U;

typedef union {
    struct {
        unsigned int pvtc_wr_lock : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PVTC_WR_LOCK_U;

typedef union {
    struct {
        unsigned int pvtc_ts_alarmb : 2; // [1:0]
        unsigned int pvtc_ts_alarma : 2; // [3:2]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PVTC_TS_ALARM_U;

typedef union {
    struct {
        unsigned int pvtc_vm_alarmb : 16; // [15:0]
        unsigned int pvtc_vm_alarma : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PVTC_VM_ALARM_U;

typedef union {
    struct {
        unsigned int pvtc_pd_alarmb : 11; // [10:0]
        unsigned int RESERVED_1 : 1; // [11]
        unsigned int pvtc_pd_alarma : 11; // [22:12]
        unsigned int RESERVED_0 : 9; // [31:23]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PVTC_PD_ALARM_U;

typedef union {
    struct {
        unsigned int e902_cnt_clr : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_E902_CNT_CLR_U;

typedef union {
    struct {
        unsigned int e902_cpu_rst_addr : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_E902_RST_ADDR_U;

typedef union {
    struct {
        unsigned int c906_cpu_rst_addr_l : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_C906_RST_ADDR_L_U;

typedef union {
    struct {
        unsigned int c906_cpu_rst_addr_h : 8; // [7:0]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_C906_RST_ADDR_H_U;

typedef union {
    struct {
        unsigned int reserved_reg_0 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_0_U;

typedef union {
    struct {
        unsigned int reserved_reg_1 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_1_U;

typedef union {
    struct {
        unsigned int reserved_reg_2 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_2_U;

typedef union {
    struct {
        unsigned int reserved_reg_3 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_3_U;

typedef union {
    struct {
        unsigned int aonsys_ahb_space_sel : 10; // [9:0]
        unsigned int RESERVED_0 : 22; // [31:10]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_AON_AHB_ADEXT_U;

typedef union {
    struct {
        unsigned int rc_en : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RC_EN_U;

typedef union {
    struct {
        unsigned int rc_fcal : 12; // [11:0]
        unsigned int RESERVED_0 : 20; // [31:12]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RC_FCAL_U;

typedef union {
    struct {
        unsigned int rc_mode : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RC_MODE_U;

typedef union {
    struct {
        unsigned int rc_ready : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RC_READY_U;

typedef union {
    struct {
        unsigned int aon_isolation_en : 1; // [0]
        unsigned int c910_isolation_en : 1; // [1]
        unsigned int ddr_isolation_en : 1; // [2]
        unsigned int usb3_isolation_en : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_ISO_CFG_U;

typedef union {
    struct {
        unsigned int int_seram_err : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_OCRAM_ERR_U;

typedef union {
    struct {
        unsigned int timer_1_2_link : 1; // [0]
        unsigned int timer_2_3_link : 1; // [1]
        unsigned int timer_3_4_link : 1; // [2]
        unsigned int RESERVED_0 : 29; // [31:3]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_TIMER_LINK_U;

typedef union {
    struct {
        unsigned int pd_req : 11; // [10:0]
        unsigned int RESERVED_1 : 5; // [15:11]
        unsigned int pu_req : 11; // [26:16]
        unsigned int RESERVED_0 : 5; // [31:27]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_REQ_U;

typedef union {
    struct {
        unsigned int pd_iso_en_set : 11; // [10:0]
        unsigned int RESERVED_0 : 21; // [31:11]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_ISO_EN_SET_U;

typedef union {
    struct {
        unsigned int pd_iso_en_clr : 11; // [10:0]
        unsigned int RESERVED_0 : 21; // [31:11]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_ISO_EN_CLR_U;

typedef union {
    struct {
        unsigned int pd_sw_en_set : 22; // [21:0]
        unsigned int RESERVED_0 : 10; // [31:22]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_SW_EN_SET_U;

typedef union {
    struct {
        unsigned int pd_sw_en_clr : 22; // [21:0]
        unsigned int RESERVED_0 : 10; // [31:22]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_SW_EN_CLR_U;

typedef union {
    struct {
        unsigned int pd_sw_ack : 22; // [21:0]
        unsigned int RESERVED_0 : 10; // [31:22]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_SW_ACK_U;

typedef union {
    struct {
        unsigned int pd_sw_cnt_en : 22; // [21:0]
        unsigned int RESERVED_0 : 10; // [31:22]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_SW_CNT_EN_U;

typedef union {
    struct {
        unsigned int pd_fsm_rst : 11; // [10:0]
        unsigned int RESERVED_0 : 21; // [31:11]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_FSM_RST_U;

typedef union {
    struct {
        unsigned int pd_int_mask : 22; // [21:0]
        unsigned int RESERVED_0 : 10; // [31:22]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_INT_MASK_U;

typedef union {
    struct {
        unsigned int pd_fsm_st_l : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_FSM_STS_L_U;

typedef union {
    struct {
        unsigned int pd_fsm_st_h : 12; // [11:0]
        unsigned int RESERVED_0 : 20; // [31:12]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_FSM_STS_H_U;

typedef union {
    struct {
        unsigned int pd_int_st : 22; // [21:0]
        unsigned int RESERVED_0 : 10; // [31:22]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_INT_STS_U;

typedef union {
    struct {
        unsigned int pd_int_clr : 22; // [21:0]
        unsigned int RESERVED_0 : 10; // [31:22]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_INT_CLR_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_0 : 16; // [15:0]
        unsigned int sw1_wait_cnt_0 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK0_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_1 : 16; // [15:0]
        unsigned int sw1_wait_cnt_1 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK1_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_2 : 16; // [15:0]
        unsigned int sw1_wait_cnt_2 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK2_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_3 : 16; // [15:0]
        unsigned int sw1_wait_cnt_3 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK3_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_4 : 16; // [15:0]
        unsigned int sw1_wait_cnt_4 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK4_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_5 : 16; // [15:0]
        unsigned int sw1_wait_cnt_5 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK5_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_6 : 16; // [15:0]
        unsigned int sw1_wait_cnt_6 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK6_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_7 : 16; // [15:0]
        unsigned int sw1_wait_cnt_7 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK7_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_8 : 16; // [15:0]
        unsigned int sw1_wait_cnt_8 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK8_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_9 : 16; // [15:0]
        unsigned int sw1_wait_cnt_9 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK9_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_wait_cnt_10 : 16; // [15:0]
        unsigned int sw1_wait_cnt_10 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK10_SW_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_0 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_0 : 12; // [19:8]
        unsigned int iso_wait_cnt_0 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK0_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_1 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_1 : 12; // [19:8]
        unsigned int iso_wait_cnt_1 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK1_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_2 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_2 : 12; // [19:8]
        unsigned int iso_wait_cnt_2 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK2_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_3 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_3 : 12; // [19:8]
        unsigned int iso_wait_cnt_3 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK3_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_4 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_4 : 12; // [19:8]
        unsigned int iso_wait_cnt_4 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK4_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_5 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_5 : 12; // [19:8]
        unsigned int iso_wait_cnt_5 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK5_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_6 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_6 : 12; // [19:8]
        unsigned int iso_wait_cnt_6 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK6_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_7 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_7 : 12; // [19:8]
        unsigned int iso_wait_cnt_7 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK7_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_8 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_8 : 12; // [19:8]
        unsigned int iso_wait_cnt_8 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK8_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_9 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_9 : 12; // [19:8]
        unsigned int iso_wait_cnt_9 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK9_INTV_CNT_U;

typedef union {
    struct {
        unsigned int sw0_sw1_wait_cnt_10 : 8; // [7:0]
        unsigned int iso_sw_wait_cnt_10 : 12; // [19:8]
        unsigned int iso_wait_cnt_10 : 12; // [31:20]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PD_BLK10_INTV_CNT_U;

typedef union {
    struct {
        unsigned int audio_pmu_req : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_AUDIO_PMU_REQ_U;

typedef union {
    struct {
        unsigned int audio_pmu_sts : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_AUDIO_PMU_STS_U;

typedef union {
    struct {
        unsigned int audio_pmu_intr_sts_raw : 1; // [0]
        unsigned int audio_pmu_intr_sts : 1; // [1]
        unsigned int audio_pmu_intr_clr : 1; // [2]
        unsigned int audio_pmu_intr_msk : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_AUDIO_PMU_INTR_U;

typedef union {
    struct {
        unsigned int pmu_audio_req : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PMU_AUDIO_REQ_U;

typedef union {
    struct {
        unsigned int pmu_audio_sts : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PMU_AUDIO_STS_U;

typedef union {
    struct {
        unsigned int c910_core0_mem_dslp : 1; // [0]
        unsigned int c910_core0_mem_slp : 1; // [1]
        unsigned int c910_core0_mem_sd : 1; // [2]
        unsigned int RESERVED_5 : 1; // [3]
        unsigned int c910_core1_mem_dslp : 1; // [4]
        unsigned int c910_core1_mem_slp : 1; // [5]
        unsigned int c910_core1_mem_sd : 1; // [6]
        unsigned int RESERVED_4 : 1; // [7]
        unsigned int c910_core2_mem_dslp : 1; // [8]
        unsigned int c910_core2_mem_slp : 1; // [9]
        unsigned int c910_core2_mem_sd : 1; // [10]
        unsigned int RESERVED_3 : 1; // [11]
        unsigned int c910_core3_mem_dslp : 1; // [12]
        unsigned int c910_core3_mem_slp : 1; // [13]
        unsigned int c910_core3_mem_sd : 1; // [14]
        unsigned int RESERVED_2 : 1; // [15]
        unsigned int c910_cpu_mem_dslp : 1; // [16]
        unsigned int c910_cpu_mem_slp : 1; // [17]
        unsigned int c910_cpu_mem_sd : 1; // [18]
        unsigned int RESERVED_1 : 1; // [19]
        unsigned int sram_axi_axi_sram_dslp : 1; // [20]
        unsigned int sram_axi_axi_sram_slp : 1; // [21]
        unsigned int sram_axi_axi_sram_sd : 1; // [22]
        unsigned int RESERVED_0 : 9; // [31:23]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_MEM_LP_MODE_U;

typedef union {
    struct {
        unsigned int c910_core0_dbg_mask : 1; // [0]
        unsigned int c910_core1_dbg_mask : 1; // [1]
        unsigned int c910_core2_dbg_mask : 1; // [2]
        unsigned int c910_core3_dbg_mask : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_C910_DBG_MASK_U;

typedef union {
    struct {
        unsigned int c910_cpu_l2cache_flush_req : 1; // [0]
        unsigned int c910_cpu_l2cache_flush_done : 1; // [1]
        unsigned int c910_cpu_no_op : 1; // [2]
        unsigned int RESERVED_0 : 29; // [31:3]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_C910_L2CACHE_U;

typedef union {
    struct {
        unsigned int bisr_bypass_lock_reg : 1; // [0]
        unsigned int bisr_bypass_reg : 1; // [1]
        unsigned int bisr_l2_done_reg : 1; // [2]
        unsigned int bisr_sram_done_reg : 1; // [3]
        unsigned int bisr_l2_cde_reg : 1; // [4]
        unsigned int bisr_sram_cde_reg : 1; // [5]
        unsigned int pad_bisr_bypass : 1; // [6]
        unsigned int RESERVED_0 : 25; // [31:7]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_BISR_CTRL_U;

typedef union {
    struct {
        unsigned int efuse_preload_done_reg : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_EFUSE_PRELOAD_DONE_U;

typedef union {
    struct {
        unsigned int gpio1_pad_irte : 1; // [0]
        unsigned int gpio2_pad_irte : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_GPIO_RTE_U;

typedef union {
    struct {
        unsigned int pll_dskewcal_bypass_lock : 1; // [0]
        unsigned int pad_pll_dskewcal_bypass : 1; // [1]
        unsigned int pll_dskewcal_bypass_reg : 1; // [2]
        unsigned int RESERVED_0 : 29; // [31:3]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_PLL_DSKEW_LOCK_U;

typedef union {
    struct {
        unsigned int sramc_init : 1; // [0]
        unsigned int sramc_ovcap_det : 1; // [1]
        unsigned int sramc_acg_en : 1; // [2]
        unsigned int RESERVED_1 : 5; // [7:3]
        unsigned int sramc_pchk_mode : 8; // [15:8]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_SRAM_AXI_CFG_U;

typedef union {
    struct {
        unsigned int sramc_ovcap_alarm : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_SRAM_AXI_ST_U;

typedef union {
    struct {
        unsigned int sramc_err_sts_0 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_0_U;

typedef union {
    struct {
        unsigned int sramc_err_sts_1 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_1_U;

typedef union {
    struct {
        unsigned int sramc_err_sts_2 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_2_U;

typedef union {
    struct {
        unsigned int sramc_err_sts_3 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_3_U;

typedef union {
    struct {
        unsigned int sramc_err_sts_4 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_4_U;

typedef union {
    struct {
        unsigned int se_rst_mux_lock : 1; // [0]
        unsigned int se_io_mux_lock : 6; // [6:1]
        unsigned int RESERVED_0 : 25; // [31:7]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_SE_MUX_LOCK_U;

typedef union {
    struct {
        unsigned int cpu_dbg_dis_lock : 3; // [2:0]
        unsigned int RESERVED_0 : 29; // [31:3]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_CPU_DBG_DIS_LOCK_U;

typedef union {
    struct {
        unsigned int reserved_reg_4 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_4_U;

typedef union {
    struct {
        unsigned int reserved_reg_5 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_5_U;

typedef union {
    struct {
        unsigned int reserved_reg_6 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_6_U;

typedef union {
    struct {
        unsigned int reserved_reg_7 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_7_U;

typedef union {
    struct {
        unsigned int reserved_reg_8 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_8_U;

typedef union {
    struct {
        unsigned int reserved_reg_9 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_9_U;

typedef union {
    struct {
        unsigned int reserved_reg_10 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_10_U;

typedef union {
    struct {
        unsigned int reserved_reg_11 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_11_U;

typedef union {
    struct {
        unsigned int reserved_reg_12 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_12_U;

typedef union {
    struct {
        unsigned int reserved_reg_13 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_13_U;

typedef union {
    struct {
        unsigned int reserved_reg_14 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_14_U;

typedef union {
    struct {
        unsigned int reserved_reg_15 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_15_U;

typedef union {
    struct {
        unsigned int reserved_reg_16 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_16_U;

typedef union {
    struct {
        unsigned int reserved_reg_17 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_17_U;

typedef union {
    struct {
        unsigned int reserved_reg_18 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_18_U;

typedef union {
    struct {
        unsigned int reserved_reg_19 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_SYSREG_REG_SW_RESERVED_REG_19_U;

typedef union {
    volatile AONSYS_SYSREG_REG_SW_CPU_LP_MODE_U aonsys_sysreg_reg_sw_cpu_lp_mode;    // 0x0
    volatile AONSYS_SYSREG_REG_SW_CHIP_LP_MODE_U aonsys_sysreg_reg_sw_chip_lp_mode;    // 0x4
    volatile AONSYS_SYSREG_REG_SW_AO_SERAM_TRN_U aonsys_sysreg_reg_sw_ao_seram_trn;    // 0x10
    volatile AONSYS_SYSREG_REG_SW_AO_SERAM_INT_U aonsys_sysreg_reg_sw_ao_seram_int;    // 0x14
    volatile AONSYS_SYSREG_REG_SW_STR_SERAM_TRN_U aonsys_sysreg_reg_sw_str_seram_trn;    // 0x18
    volatile AONSYS_SYSREG_REG_SW_STR_SERAM_INT_U aonsys_sysreg_reg_sw_str_seram_int;    // 0x1c
    volatile AONSYS_SYSREG_REG_SW_STR_INDICATOR_0_U aonsys_sysreg_reg_sw_str_indicator_0;    // 0x20
    volatile AONSYS_SYSREG_REG_SW_STR_INDICATOR_1_U aonsys_sysreg_reg_sw_str_indicator_1;    // 0x24
    volatile AONSYS_SYSREG_REG_SW_STR_INDICATOR_2_U aonsys_sysreg_reg_sw_str_indicator_2;    // 0x28
    volatile AONSYS_SYSREG_REG_SW_STR_INDICATOR_3_U aonsys_sysreg_reg_sw_str_indicator_3;    // 0x2c
    volatile AONSYS_SYSREG_REG_SW_PVTC_WR_LOCK_U aonsys_sysreg_reg_sw_pvtc_wr_lock;    // 0x30
    volatile AONSYS_SYSREG_REG_SW_PVTC_TS_ALARM_U aonsys_sysreg_reg_sw_pvtc_ts_alarm;    // 0x34
    volatile AONSYS_SYSREG_REG_SW_PVTC_VM_ALARM_U aonsys_sysreg_reg_sw_pvtc_vm_alarm;    // 0x38
    volatile AONSYS_SYSREG_REG_SW_PVTC_PD_ALARM_U aonsys_sysreg_reg_sw_pvtc_pd_alarm;    // 0x3c
    volatile AONSYS_SYSREG_REG_SW_E902_CNT_CLR_U aonsys_sysreg_reg_sw_e902_cnt_clr;    // 0x40
    volatile AONSYS_SYSREG_REG_SW_E902_RST_ADDR_U aonsys_sysreg_reg_sw_e902_rst_addr;    // 0x44
    volatile AONSYS_SYSREG_REG_SW_C906_RST_ADDR_L_U aonsys_sysreg_reg_sw_c906_rst_addr_l;    // 0x48
    volatile AONSYS_SYSREG_REG_SW_C906_RST_ADDR_H_U aonsys_sysreg_reg_sw_c906_rst_addr_h;    // 0x4c
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_0_U aonsys_sysreg_reg_sw_reserved_reg_0;    // 0x50
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_1_U aonsys_sysreg_reg_sw_reserved_reg_1;    // 0x54
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_2_U aonsys_sysreg_reg_sw_reserved_reg_2;    // 0x58
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_3_U aonsys_sysreg_reg_sw_reserved_reg_3;    // 0x5c
    volatile AONSYS_SYSREG_REG_SW_AON_AHB_ADEXT_U aonsys_sysreg_reg_sw_aon_ahb_adext;    // 0x60
    volatile AONSYS_SYSREG_REG_SW_RC_EN_U aonsys_sysreg_reg_sw_rc_en;    // 0x70
    volatile AONSYS_SYSREG_REG_SW_RC_FCAL_U aonsys_sysreg_reg_sw_rc_fcal;    // 0x74
    volatile AONSYS_SYSREG_REG_SW_RC_MODE_U aonsys_sysreg_reg_sw_rc_mode;    // 0x78
    volatile AONSYS_SYSREG_REG_SW_RC_READY_U aonsys_sysreg_reg_sw_rc_ready;    // 0x7c
    volatile AONSYS_SYSREG_REG_SW_ISO_CFG_U aonsys_sysreg_reg_sw_iso_cfg;    // 0x80
    volatile AONSYS_SYSREG_REG_SW_OCRAM_ERR_U aonsys_sysreg_reg_sw_ocram_err;    // 0x90
    volatile AONSYS_SYSREG_REG_SW_TIMER_LINK_U aonsys_sysreg_reg_sw_timer_link;    // 0x100
    volatile AONSYS_SYSREG_REG_SW_PD_REQ_U aonsys_sysreg_reg_sw_pd_req;    // 0x110
    volatile AONSYS_SYSREG_REG_SW_PD_ISO_EN_SET_U aonsys_sysreg_reg_sw_pd_iso_en_set;    // 0x114
    volatile AONSYS_SYSREG_REG_SW_PD_ISO_EN_CLR_U aonsys_sysreg_reg_sw_pd_iso_en_clr;    // 0x118
    volatile AONSYS_SYSREG_REG_SW_PD_SW_EN_SET_U aonsys_sysreg_reg_sw_pd_sw_en_set;    // 0x11c
    volatile AONSYS_SYSREG_REG_SW_PD_SW_EN_CLR_U aonsys_sysreg_reg_sw_pd_sw_en_clr;    // 0x120
    volatile AONSYS_SYSREG_REG_SW_PD_SW_ACK_U aonsys_sysreg_reg_sw_pd_sw_ack;    // 0x124
    volatile AONSYS_SYSREG_REG_SW_PD_SW_CNT_EN_U aonsys_sysreg_reg_sw_pd_sw_cnt_en;    // 0x128
    volatile AONSYS_SYSREG_REG_SW_PD_FSM_RST_U aonsys_sysreg_reg_sw_pd_fsm_rst;    // 0x12c
    volatile AONSYS_SYSREG_REG_SW_PD_INT_MASK_U aonsys_sysreg_reg_sw_pd_int_mask;    // 0x130
    volatile AONSYS_SYSREG_REG_SW_PD_FSM_STS_L_U aonsys_sysreg_reg_sw_pd_fsm_sts_l;    // 0x134
    volatile AONSYS_SYSREG_REG_SW_PD_FSM_STS_H_U aonsys_sysreg_reg_sw_pd_fsm_sts_h;    // 0x138
    volatile AONSYS_SYSREG_REG_SW_PD_INT_STS_U aonsys_sysreg_reg_sw_pd_int_sts;    // 0x13c
    volatile AONSYS_SYSREG_REG_SW_PD_INT_CLR_U aonsys_sysreg_reg_sw_pd_int_clr;    // 0x140
    volatile AONSYS_SYSREG_REG_SW_PD_BLK0_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk0_sw_cnt;    // 0x144
    volatile AONSYS_SYSREG_REG_SW_PD_BLK1_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk1_sw_cnt;    // 0x148
    volatile AONSYS_SYSREG_REG_SW_PD_BLK2_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk2_sw_cnt;    // 0x14c
    volatile AONSYS_SYSREG_REG_SW_PD_BLK3_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk3_sw_cnt;    // 0x150
    volatile AONSYS_SYSREG_REG_SW_PD_BLK4_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk4_sw_cnt;    // 0x154
    volatile AONSYS_SYSREG_REG_SW_PD_BLK5_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk5_sw_cnt;    // 0x158
    volatile AONSYS_SYSREG_REG_SW_PD_BLK6_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk6_sw_cnt;    // 0x15c
    volatile AONSYS_SYSREG_REG_SW_PD_BLK7_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk7_sw_cnt;    // 0x160
    volatile AONSYS_SYSREG_REG_SW_PD_BLK8_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk8_sw_cnt;    // 0x164
    volatile AONSYS_SYSREG_REG_SW_PD_BLK9_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk9_sw_cnt;    // 0x168
    volatile AONSYS_SYSREG_REG_SW_PD_BLK10_SW_CNT_U aonsys_sysreg_reg_sw_pd_blk10_sw_cnt;    // 0x16c
    volatile AONSYS_SYSREG_REG_SW_PD_BLK0_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk0_intv_cnt;    // 0x180
    volatile AONSYS_SYSREG_REG_SW_PD_BLK1_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk1_intv_cnt;    // 0x184
    volatile AONSYS_SYSREG_REG_SW_PD_BLK2_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk2_intv_cnt;    // 0x188
    volatile AONSYS_SYSREG_REG_SW_PD_BLK3_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk3_intv_cnt;    // 0x18c
    volatile AONSYS_SYSREG_REG_SW_PD_BLK4_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk4_intv_cnt;    // 0x190
    volatile AONSYS_SYSREG_REG_SW_PD_BLK5_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk5_intv_cnt;    // 0x194
    volatile AONSYS_SYSREG_REG_SW_PD_BLK6_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk6_intv_cnt;    // 0x198
    volatile AONSYS_SYSREG_REG_SW_PD_BLK7_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk7_intv_cnt;    // 0x19c
    volatile AONSYS_SYSREG_REG_SW_PD_BLK8_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk8_intv_cnt;    // 0x1a0
    volatile AONSYS_SYSREG_REG_SW_PD_BLK9_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk9_intv_cnt;    // 0x1a4
    volatile AONSYS_SYSREG_REG_SW_PD_BLK10_INTV_CNT_U aonsys_sysreg_reg_sw_pd_blk10_intv_cnt;    // 0x1a8
    volatile AONSYS_SYSREG_REG_SW_AUDIO_PMU_REQ_U aonsys_sysreg_reg_sw_audio_pmu_req;    // 0x1f8
    volatile AONSYS_SYSREG_REG_SW_AUDIO_PMU_STS_U aonsys_sysreg_reg_sw_audio_pmu_sts;    // 0x1fc
    volatile AONSYS_SYSREG_REG_SW_AUDIO_PMU_INTR_U aonsys_sysreg_reg_sw_audio_pmu_intr;    // 0x204
    volatile AONSYS_SYSREG_REG_SW_PMU_AUDIO_REQ_U aonsys_sysreg_reg_sw_pmu_audio_req;    // 0x208
    volatile AONSYS_SYSREG_REG_SW_PMU_AUDIO_STS_U aonsys_sysreg_reg_sw_pmu_audio_sts;    // 0x20c
    volatile AONSYS_SYSREG_REG_SW_MEM_LP_MODE_U aonsys_sysreg_reg_sw_mem_lp_mode;    // 0x210
    volatile AONSYS_SYSREG_REG_SW_C910_DBG_MASK_U aonsys_sysreg_reg_sw_c910_dbg_mask;    // 0x214
    volatile AONSYS_SYSREG_REG_SW_C910_L2CACHE_U aonsys_sysreg_reg_sw_c910_l2cache;    // 0x218
    volatile AONSYS_SYSREG_REG_SW_BISR_CTRL_U aonsys_sysreg_reg_sw_bisr_ctrl;    // 0x220
    volatile AONSYS_SYSREG_REG_SW_EFUSE_PRELOAD_DONE_U aonsys_sysreg_reg_sw_efuse_preload_done;    // 0x224
    volatile AONSYS_SYSREG_REG_SW_GPIO_RTE_U aonsys_sysreg_reg_sw_gpio_rte;    // 0x228
    volatile AONSYS_SYSREG_REG_SW_PLL_DSKEW_LOCK_U aonsys_sysreg_reg_sw_pll_dskew_lock;    // 0x22c
    volatile AONSYS_SYSREG_REG_SW_SRAM_AXI_CFG_U aonsys_sysreg_reg_sw_sram_axi_cfg;    // 0x230
    volatile AONSYS_SYSREG_REG_SW_SRAM_AXI_ST_U aonsys_sysreg_reg_sw_sram_axi_st;    // 0x234
    volatile AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_0_U aonsys_sysreg_reg_sw_sram_axi_err_sts_0;    // 0x238
    volatile AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_1_U aonsys_sysreg_reg_sw_sram_axi_err_sts_1;    // 0x23c
    volatile AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_2_U aonsys_sysreg_reg_sw_sram_axi_err_sts_2;    // 0x240
    volatile AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_3_U aonsys_sysreg_reg_sw_sram_axi_err_sts_3;    // 0x244
    volatile AONSYS_SYSREG_REG_SW_SRAM_AXI_ERR_STS_4_U aonsys_sysreg_reg_sw_sram_axi_err_sts_4;    // 0x248
    volatile AONSYS_SYSREG_REG_SW_SE_MUX_LOCK_U aonsys_sysreg_reg_sw_se_mux_lock;    // 0x24c
    volatile AONSYS_SYSREG_REG_SW_CPU_DBG_DIS_LOCK_U aonsys_sysreg_reg_sw_cpu_dbg_dis_lock;    // 0x270
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_4_U aonsys_sysreg_reg_sw_reserved_reg_4;    // 0x300
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_5_U aonsys_sysreg_reg_sw_reserved_reg_5;    // 0x304
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_6_U aonsys_sysreg_reg_sw_reserved_reg_6;    // 0x308
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_7_U aonsys_sysreg_reg_sw_reserved_reg_7;    // 0x30c
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_8_U aonsys_sysreg_reg_sw_reserved_reg_8;    // 0x400
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_9_U aonsys_sysreg_reg_sw_reserved_reg_9;    // 0x404
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_10_U aonsys_sysreg_reg_sw_reserved_reg_10;    // 0x408
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_11_U aonsys_sysreg_reg_sw_reserved_reg_11;    // 0x40c
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_12_U aonsys_sysreg_reg_sw_reserved_reg_12;    // 0x500
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_13_U aonsys_sysreg_reg_sw_reserved_reg_13;    // 0x504
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_14_U aonsys_sysreg_reg_sw_reserved_reg_14;    // 0x508
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_15_U aonsys_sysreg_reg_sw_reserved_reg_15;    // 0x50c
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_16_U aonsys_sysreg_reg_sw_reserved_reg_16;    // 0x600
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_17_U aonsys_sysreg_reg_sw_reserved_reg_17;    // 0x604
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_18_U aonsys_sysreg_reg_sw_reserved_reg_18;    // 0x608
    volatile AONSYS_SYSREG_REG_SW_RESERVED_REG_19_U aonsys_sysreg_reg_sw_reserved_reg_19;    // 0x60c
} AONSYS_SYSREG_REG_SW_REG_S;
	
#endif
	
	
