//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef AONSYS_RSTGEN_REG_SW_H
#define AONSYS_RSTGEN_REG_SW_H

typedef union {
    struct {
        unsigned int r_rst_cnt : 8; // [7:0]
        unsigned int r_dly_cnt : 8; // [15:8]
        unsigned int r_rst_cnt_en : 1; // [16]
        unsigned int r_dly_cnt_en : 1; // [17]
        unsigned int RESERVED_0 : 14; // [31:18]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_CNT_U;

typedef union {
    struct {
        unsigned int sw_sys_rst_req : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_SYS_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_rtc_prst_n : 1; // [0]
        unsigned int sw_rtc_crst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RTC_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_aogpio_dbclk_rst_n : 1; // [0]
        unsigned int sw_aogpio_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_AOGPIO_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_aoi2c_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_AOI2C_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_pvtc_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_PVTC_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_e902_crst_n : 1; // [0]
        unsigned int sw_e902_had_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_E902_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_aotimer_prst_n : 1; // [0]
        unsigned int sw_aotimer_crst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_AOTIMER_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_aowdt_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_AOWDT_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_apsys_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_APSYS_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_npusys_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_NPUSYS_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_ddrsys_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_DDRSYS_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_audio_subsys_arst_n_ap2cp : 1; // [0]
        unsigned int sw_audio_subsys_arst_n_cp2ap : 1; // [1]
        unsigned int sw_audio_subsys_arst_n_cp2sram : 1; // [2]
        unsigned int sw_audio_subsys_crst_n : 1; // [3]
        unsigned int sw_audio_subsys_iopmp_cp_rst_n : 1; // [4]
        unsigned int sw_audio_rst_n : 1; // [5]
        unsigned int RESERVED_0 : 26; // [31:6]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_AUDIO_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_bisr_sram_rst_n : 1; // [0]
        unsigned int sw_bisr_l2_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_BISR_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_dsp0_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_DSP0_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_dsp1_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_DSP1_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_gpu_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_GPU_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_vdec_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_VDEC_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_venc_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_VENC_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_adc_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_ADC_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_audgpio_dbclk_rst_n : 1; // [0]
        unsigned int sw_audgpio_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_AUDGPIO_RST_CFG_U;

typedef union {
    struct {
        unsigned int sw_aouart_s_rst_n : 1; // [0]
        unsigned int sw_aouart_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_AOUART_RST_CFG_U;

typedef union {
    struct {
        unsigned int r_rst_clr_0 : 2; // [1:0]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_CLR_0_U;

typedef union {
    struct {
        unsigned int r_rst_clr_1 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_CLR_1_U;

typedef union {
    struct {
        unsigned int r_rst_clr_2 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_CLR_2_U;

typedef union {
    struct {
        unsigned int r_rst_clr_3 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_CLR_3_U;

typedef union {
    struct {
        unsigned int r_rst_clr_4 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_CLR_4_U;

typedef union {
    struct {
        unsigned int r_rst_sts_0 : 2; // [1:0]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_STS_0_U;

typedef union {
    struct {
        unsigned int r_rst_sts_1 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_STS_1_U;

typedef union {
    struct {
        unsigned int r_rst_sts_2 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_STS_2_U;

typedef union {
    struct {
        unsigned int r_rst_sts_3 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_STS_3_U;

typedef union {
    struct {
        unsigned int r_rst_sts_4 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_STS_4_U;

typedef union {
    struct {
        unsigned int r_rst_req_en_0 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_REQ_EN_0_U;

typedef union {
    struct {
        unsigned int r_rst_req_en_1 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_REQ_EN_1_U;

typedef union {
    struct {
        unsigned int r_rst_req_en_2 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_REQ_EN_2_U;

typedef union {
    struct {
        unsigned int r_rst_req_en_3 : 32; // [31:0]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_RST_REQ_EN_3_U;

typedef union {
    struct {
        unsigned int sw_sram_axi_arst_n_0 : 1; // [0]
        unsigned int sw_sram_axi_arst_n_1 : 1; // [1]
        unsigned int sw_sram_axi_arst_n_2 : 1; // [2]
        unsigned int sw_sram_axi_arst_n_3 : 1; // [3]
        unsigned int sw_sram_axi_arst_n_4 : 1; // [4]
        unsigned int RESERVED_1 : 1; // [5]
        unsigned int sw_sram_axi_core_rst_n : 1; // [6]
        unsigned int RESERVED_0 : 25; // [31:7]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_SRAM_AXI_RST_CFG_U;

typedef union {
    struct {
        unsigned int pad_se_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} AONSYS_RSTGEN_REG_SW_SE_RST_CFG_U;

typedef union {
    volatile AONSYS_RSTGEN_REG_SW_RST_CNT_U aonsys_rstgen_reg_sw_rst_cnt;    // 0x0
    volatile AONSYS_RSTGEN_REG_SW_SYS_RST_CFG_U aonsys_rstgen_reg_sw_sys_rst_cfg;    // 0x10
    volatile AONSYS_RSTGEN_REG_SW_RTC_RST_CFG_U aonsys_rstgen_reg_sw_rtc_rst_cfg;    // 0x14
    volatile AONSYS_RSTGEN_REG_SW_AOGPIO_RST_CFG_U aonsys_rstgen_reg_sw_aogpio_rst_cfg;    // 0x18
    volatile AONSYS_RSTGEN_REG_SW_AOI2C_RST_CFG_U aonsys_rstgen_reg_sw_aoi2c_rst_cfg;    // 0x1c
    volatile AONSYS_RSTGEN_REG_SW_PVTC_RST_CFG_U aonsys_rstgen_reg_sw_pvtc_rst_cfg;    // 0x20
    volatile AONSYS_RSTGEN_REG_SW_E902_RST_CFG_U aonsys_rstgen_reg_sw_e902_rst_cfg;    // 0x24
    volatile AONSYS_RSTGEN_REG_SW_AOTIMER_RST_CFG_U aonsys_rstgen_reg_sw_aotimer_rst_cfg;    // 0x28
    volatile AONSYS_RSTGEN_REG_SW_AOWDT_RST_CFG_U aonsys_rstgen_reg_sw_aowdt_rst_cfg;    // 0x2c
    volatile AONSYS_RSTGEN_REG_SW_APSYS_RST_CFG_U aonsys_rstgen_reg_sw_apsys_rst_cfg;    // 0x30
    volatile AONSYS_RSTGEN_REG_SW_NPUSYS_RST_CFG_U aonsys_rstgen_reg_sw_npusys_rst_cfg;    // 0x34
    volatile AONSYS_RSTGEN_REG_SW_DDRSYS_RST_CFG_U aonsys_rstgen_reg_sw_ddrsys_rst_cfg;    // 0x38
    volatile AONSYS_RSTGEN_REG_SW_AUDIO_RST_CFG_U aonsys_rstgen_reg_sw_audio_rst_cfg;    // 0x3c
    volatile AONSYS_RSTGEN_REG_SW_BISR_RST_CFG_U aonsys_rstgen_reg_sw_bisr_rst_cfg;    // 0x50
    volatile AONSYS_RSTGEN_REG_SW_DSP0_RST_CFG_U aonsys_rstgen_reg_sw_dsp0_rst_cfg;    // 0x54
    volatile AONSYS_RSTGEN_REG_SW_DSP1_RST_CFG_U aonsys_rstgen_reg_sw_dsp1_rst_cfg;    // 0x58
    volatile AONSYS_RSTGEN_REG_SW_GPU_RST_CFG_U aonsys_rstgen_reg_sw_gpu_rst_cfg;    // 0x5c
    volatile AONSYS_RSTGEN_REG_SW_VDEC_RST_CFG_U aonsys_rstgen_reg_sw_vdec_rst_cfg;    // 0x60
    volatile AONSYS_RSTGEN_REG_SW_VENC_RST_CFG_U aonsys_rstgen_reg_sw_venc_rst_cfg;    // 0x64
    volatile AONSYS_RSTGEN_REG_SW_ADC_RST_CFG_U aonsys_rstgen_reg_sw_adc_rst_cfg;    // 0x70
    volatile AONSYS_RSTGEN_REG_SW_AUDGPIO_RST_CFG_U aonsys_rstgen_reg_sw_audgpio_rst_cfg;    // 0x74
    volatile AONSYS_RSTGEN_REG_SW_AOUART_RST_CFG_U aonsys_rstgen_reg_sw_aouart_rst_cfg;    // 0x78
    volatile AONSYS_RSTGEN_REG_SW_RST_CLR_0_U aonsys_rstgen_reg_sw_rst_clr_0;    // 0x100
    volatile AONSYS_RSTGEN_REG_SW_RST_CLR_1_U aonsys_rstgen_reg_sw_rst_clr_1;    // 0x104
    volatile AONSYS_RSTGEN_REG_SW_RST_CLR_2_U aonsys_rstgen_reg_sw_rst_clr_2;    // 0x108
    volatile AONSYS_RSTGEN_REG_SW_RST_CLR_3_U aonsys_rstgen_reg_sw_rst_clr_3;    // 0x10c
    volatile AONSYS_RSTGEN_REG_SW_RST_CLR_4_U aonsys_rstgen_reg_sw_rst_clr_4;    // 0x110
    volatile AONSYS_RSTGEN_REG_SW_RST_STS_0_U aonsys_rstgen_reg_sw_rst_sts_0;    // 0x120
    volatile AONSYS_RSTGEN_REG_SW_RST_STS_1_U aonsys_rstgen_reg_sw_rst_sts_1;    // 0x124
    volatile AONSYS_RSTGEN_REG_SW_RST_STS_2_U aonsys_rstgen_reg_sw_rst_sts_2;    // 0x128
    volatile AONSYS_RSTGEN_REG_SW_RST_STS_3_U aonsys_rstgen_reg_sw_rst_sts_3;    // 0x12c
    volatile AONSYS_RSTGEN_REG_SW_RST_STS_4_U aonsys_rstgen_reg_sw_rst_sts_4;    // 0x130
    volatile AONSYS_RSTGEN_REG_SW_RST_REQ_EN_0_U aonsys_rstgen_reg_sw_rst_req_en_0;    // 0x140
    volatile AONSYS_RSTGEN_REG_SW_RST_REQ_EN_1_U aonsys_rstgen_reg_sw_rst_req_en_1;    // 0x144
    volatile AONSYS_RSTGEN_REG_SW_RST_REQ_EN_2_U aonsys_rstgen_reg_sw_rst_req_en_2;    // 0x148
    volatile AONSYS_RSTGEN_REG_SW_RST_REQ_EN_3_U aonsys_rstgen_reg_sw_rst_req_en_3;    // 0x14c
    volatile AONSYS_RSTGEN_REG_SW_SRAM_AXI_RST_CFG_U aonsys_rstgen_reg_sw_sram_axi_rst_cfg;    // 0x11f4
    volatile AONSYS_RSTGEN_REG_SW_SE_RST_CFG_U aonsys_rstgen_reg_sw_se_rst_cfg;    // 0x160
} AONSYS_RSTGEN_REG_SW_REG_S;

#endif
