//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef APSYS_RSTGEN_REG_SW_H
#define APSYS_RSTGEN_REG_SW_H

typedef union {
    struct {
        unsigned int sw_c910_brom_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_C910_BROM_SWRST_U;

typedef union {
    struct {
        unsigned int sw_c910_rst_n : 1; // [0]
        unsigned int sw_c910_core0_rst_n : 1; // [1]
        unsigned int sw_c910_core1_rst_n : 1; // [2]
        unsigned int sw_c910_core2_rst_n : 1; // [3]
        unsigned int sw_c910_core3_rst_n : 1; // [4]
        unsigned int RESERVED_0 : 27; // [31:5]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_C910_SWRST_U;

typedef union {
    struct {
        unsigned int sw_chip_dbg_crst_n : 1; // [0]
        unsigned int sw_chip_dbg_arst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CHIP_DBG_SWRST_U;

typedef union {
    struct {
        unsigned int sw_axi4_cpusys2_arst_n : 1; // [0]
        unsigned int sw_axi4_cpusys2_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AXI4_CPUSYS2_SWRST_U;

typedef union {
    struct {
        unsigned int sw_x2x_cpusys_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_X2X_CPUSYS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_x2h_cpusys_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_X2H_CPUSYS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_ahb2_cpusys_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AHB2_CPUSYS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_apb3_cpusys_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_APB3_CPUSYS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_mbox0_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MBOX0_SWRST_U;

typedef union {
    struct {
        unsigned int sw_mbox1_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MBOX1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_mbox2_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MBOX2_SWRST_U;

typedef union {
    struct {
        unsigned int sw_mbox3_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MBOX3_SWRST_U;

typedef union {
    struct {
        unsigned int sw_wdt0_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_WDT0_SWRST_U;

typedef union {
    struct {
        unsigned int sw_wdt1_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_WDT1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_timer0_prst_n : 1; // [0]
        unsigned int sw_timer0_crst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_TIMER0_SWRST_U;

typedef union {
    struct {
        unsigned int sw_timer1_prst_n : 1; // [0]
        unsigned int sw_timer1_crst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_TIMER1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_perisys_ahb_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERISYS_AHB_SWRST_U;

typedef union {
    struct {
        unsigned int sw_perisys_apb1_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERISYS_APB1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_perisys_apb2_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERISYS_APB2_SWRST_U;

typedef union {
    struct {
        unsigned int sw_gmac0_prst_n : 1; // [0]
        unsigned int sw_gmac0_hrst_n : 1; // [1]
        unsigned int sw_gmac0_grst_n : 1; // [2]
        unsigned int sw_gmac0_arst_n : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GMAC0_SWRST_U;

typedef union {
    struct {
        unsigned int sw_uart0_prst_n : 1; // [0]
        unsigned int sw_uart0_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART0_SWRST_U;

typedef union {
    struct {
        unsigned int sw_uart1_prst_n : 1; // [0]
        unsigned int sw_uart1_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_uart2_prst_n : 1; // [0]
        unsigned int sw_uart2_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART2_SWRST_U;

typedef union {
    struct {
        unsigned int sw_uart3_prst_n : 1; // [0]
        unsigned int sw_uart3_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART3_SWRST_U;

typedef union {
    struct {
        unsigned int sw_uart4_prst_n : 1; // [0]
        unsigned int sw_uart4_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART4_SWRST_U;

typedef union {
    struct {
        unsigned int sw_uart5_prst_n : 1; // [0]
        unsigned int sw_uart5_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART5_SWRST_U;

typedef union {
    struct {
        unsigned int sw_qspi0_ssi_rst_n : 1; // [0]
        unsigned int sw_qspi0_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_QSPI0_SWRST_U;

typedef union {
    struct {
        unsigned int sw_qspi1_ssi_rst_n : 1; // [0]
        unsigned int sw_qspi1_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_QSPI1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_spi_ssi_rst_n : 1; // [0]
        unsigned int sw_spi_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_SPI_SWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c0_prst_n : 1; // [0]
        unsigned int sw_i2c0_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C0_SWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c1_prst_n : 1; // [0]
        unsigned int sw_i2c1_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c2_prst_n : 1; // [0]
        unsigned int sw_i2c2_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C2_SWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c3_prst_n : 1; // [0]
        unsigned int sw_i2c3_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C3_SWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c4_prst_n : 1; // [0]
        unsigned int sw_i2c4_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C4_SWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c5_prst_n : 1; // [0]
        unsigned int sw_i2c5_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C5_SWRST_U;

typedef union {
    struct {
        unsigned int sw_gpio0_dbrst_n : 1; // [0]
        unsigned int sw_gpio0_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GPIO0_SWRST_U;

typedef union {
    struct {
        unsigned int sw_gpio1_dbrst_n : 1; // [0]
        unsigned int sw_gpio1_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GPIO1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_gpio2_dbrst_n : 1; // [0]
        unsigned int sw_gpio2_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GPIO2_SWRST_U;

typedef union {
    struct {
        unsigned int sw_pwm_crst_n : 1; // [0]
        unsigned int sw_pwm_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PWM_SWRST_U;

typedef union {
    struct {
        unsigned int sw_padctrl0_apsys_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PADCTRL0_APSYS_SWRST_U;

typedef union {
    struct {
        unsigned int RESERVED_1 : 1; // [0]
        unsigned int sw_cpu2peri_x2h_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2PERI_X2H_SWRST_U;

typedef union {
    struct {
        unsigned int sw_axi4_cfg_bus_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AXI4_CFG_BUS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2cfg_apb_rst_n : 1; // [0]
        unsigned int sw_cpu2cfg_x2h_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2CFG_X2H_SWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2cfg_x2x_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2CFG_X2X_SWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2aon_x2h_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2AON_X2H_SWRST_U;

typedef union {
    struct {
        unsigned int sw_axi4_cpusys1_arst_n : 1; // [0]
        unsigned int sw_axi4_cpusys1_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AXI4_CPUSYS1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_aon2cpu_a2x_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AON2CPU_A2X_SWRST_U;

typedef union {
    struct {
        unsigned int reserved_reg_1 : 32; // [31:0]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RESERVED_REG_1_U;

typedef union {
    struct {
        unsigned int reserved_reg_2 : 32; // [31:0]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RESERVED_REG_2_U;

typedef union {
    struct {
        unsigned int reserved_reg_3 : 32; // [31:0]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RESERVED_REG_3_U;

typedef union {
    struct {
        unsigned int reserved_reg_4 : 32; // [31:0]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RESERVED_REG_4_U;

typedef union {
    struct {
        unsigned int sw_npusys_axi_arst_n : 1; // [0]
        unsigned int sw_npusys_axi_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_NPUSYS_AXI_SWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2vp_x2p_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2VP_X2P_SWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2vi_x2h_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2VI_X2H_SWRST_U;

typedef union {
    struct {
        unsigned int sw_bmu_c910_arst_n : 1; // [0]
        unsigned int sw_bmu_c910_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_BMU_C910_SWRST_U;

typedef union {
    struct {
        unsigned int sw_dmac_cpusys_arst_n : 1; // [0]
        unsigned int sw_dmac_cpusys_hrst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_DMAC_CPUSYS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_spinlock_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_SPINLOCK_SWRST_U;

typedef union {
    struct {
        unsigned int sw_cfg2tee_x2h_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CFG2TEE_X2H_SWRST_U;

typedef union {
    struct {
        unsigned int sw_dsmart_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_DSMART_SWRST_U;

typedef union {
    struct {
        unsigned int sw_gpio3_dbrst_n : 1; // [0]
        unsigned int sw_gpio3_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GPIO3_SWRST_U;

typedef union {
    struct {
        unsigned int sw_i2s_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2S_SWRST_U;

typedef union {
    struct {
        unsigned int sw_img_nna_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_IMG_NNA_SWRST_U;

typedef union {
    struct {
        unsigned int sw_peri_apb3_hrst_n : 1; // [0]
        unsigned int sw_peri2peri1_apb_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERI_APB3_SWRST_U;

typedef union {
    struct {
        unsigned int sw_vp_subsys_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_VP_SUBSYS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_perisys_apb4_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERISYS_APB4_SWRST_U;

typedef union {
    struct {
        unsigned int sw_gmac1_prst_n : 1; // [0]
        unsigned int sw_gmac1_hrst_n : 1; // [1]
        unsigned int sw_gmac1_grst_n : 1; // [2]
        unsigned int sw_gmac1_arst_n : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GMAC1_SWRST_U;

typedef union {
    struct {
        unsigned int sw_gmac_axi_arst_n : 1; // [0]
        unsigned int sw_gmac_axi_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GMAC_AXI_SWRST_U;

typedef union {
    struct {
        unsigned int sw_padctrl1_apsys_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PADCTRL1_APSYS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_vosys_axi_arst_n : 1; // [0]
        unsigned int sw_vosys_axi_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_VOSYS_AXI_SWRST_U;

typedef union {
    struct {
        unsigned int sw_vobus2npubus_x2x_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_VOSYS_X2X_SWRST_U;

typedef union {
    struct {
        unsigned int sw_misc2vp_x2x_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MISC2VP_X2X_SWRST_U;

typedef union {
    struct {
        unsigned int dsp_subsys_rst_n : 1; // [0]
        unsigned int vi_subsys_rst_n : 1; // [1]
        unsigned int vo_subsys_rst_n : 1; // [2]
        unsigned int vp_subsys_rst_n : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_SUBSYS_SWRST_U;

typedef union {
    struct {
        unsigned int sw_c910_brom_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_C910_BROM_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_c910_rst_n : 1; // [0]
        unsigned int sw_c910_core0_rst_n : 1; // [1]
        unsigned int sw_c910_core1_rst_n : 1; // [2]
        unsigned int sw_c910_core2_rst_n : 1; // [3]
        unsigned int sw_c910_core3_rst_n : 1; // [4]
        unsigned int RESERVED_0 : 27; // [31:5]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_C910_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_c910_top_core0_ds_rst_n : 1; // [0]
        unsigned int sw_c910_top_core1_ds_rst_n : 1; // [1]
        unsigned int sw_c910_top_core2_ds_rst_n : 1; // [2]
        unsigned int sw_c910_top_core3_ds_rst_n : 1; // [3]
        unsigned int sw_c910_top_ds_prst_n : 1; // [4]
        unsigned int RESERVED_0 : 27; // [31:5]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_C910_DS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_chip_dbg_crst_n : 1; // [0]
        unsigned int sw_chip_dbg_arst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CHIP_DBG_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_axi4_cpusys2_arst_n : 1; // [0]
        unsigned int sw_axi4_cpusys2_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AXI4_CPUSYS2_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_x2x_cpusys_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_X2X_CPUSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_x2h_cpusys_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_X2H_CPUSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_ahb2_cpusys_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AHB2_CPUSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_apb3_cpusys_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_APB3_CPUSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_mbox0_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MBOX0_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_mbox1_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MBOX1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_mbox2_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MBOX2_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_mbox3_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MBOX3_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_wdt0_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_WDT0_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_wdt1_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_WDT1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_timer0_prst_n : 1; // [0]
        unsigned int sw_timer0_crst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_TIMER0_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_timer1_prst_n : 1; // [0]
        unsigned int sw_timer1_crst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_TIMER1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_perisys_ahb_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERISYS_AHB_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_perisys_apb1_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERISYS_APB1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_perisys_apb2_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERISYS_APB2_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_gmac0_prst_n : 1; // [0]
        unsigned int sw_gmac0_hrst_n : 1; // [1]
        unsigned int sw_gmac0_grst_n : 1; // [2]
        unsigned int sw_gmac0_arst_n : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GMAC0_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_uart0_prst_n : 1; // [0]
        unsigned int sw_uart0_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART0_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_uart1_prst_n : 1; // [0]
        unsigned int sw_uart1_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_uart2_prst_n : 1; // [0]
        unsigned int sw_uart2_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART2_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_uart3_prst_n : 1; // [0]
        unsigned int sw_uart3_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART3_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_uart4_prst_n : 1; // [0]
        unsigned int sw_uart4_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART4_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_uart5_prst_n : 1; // [0]
        unsigned int sw_uart5_s_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_UART5_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_qspi0_ssi_rst_n : 1; // [0]
        unsigned int sw_qspi0_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_QSPI0_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_qspi1_ssi_rst_n : 1; // [0]
        unsigned int sw_qspi1_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_QSPI1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_spi_ssi_rst_n : 1; // [0]
        unsigned int sw_spi_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_SPI_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c0_prst_n : 1; // [0]
        unsigned int sw_i2c0_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C0_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c1_prst_n : 1; // [0]
        unsigned int sw_i2c1_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c2_prst_n : 1; // [0]
        unsigned int sw_i2c2_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C2_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c3_prst_n : 1; // [0]
        unsigned int sw_i2c3_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C3_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c4_prst_n : 1; // [0]
        unsigned int sw_i2c4_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C4_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_i2c5_prst_n : 1; // [0]
        unsigned int sw_i2c5_ic_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2C5_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_gpio0_dbrst_n : 1; // [0]
        unsigned int sw_gpio0_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GPIO0_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_gpio1_dbrst_n : 1; // [0]
        unsigned int sw_gpio1_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GPIO1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_gpio2_dbrst_n : 1; // [0]
        unsigned int sw_gpio2_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GPIO2_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_pwm_crst_n : 1; // [0]
        unsigned int sw_pwm_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PWM_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_padctrl0_apsys_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PADCTRL0_APSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int RESERVED_1 : 1; // [0]
        unsigned int sw_cpu2peri_x2h_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2PERI_X2H_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_axi4_cfg_bus_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AXI4_CFG_BUS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2cfg_apb_rst_n : 1; // [0]
        unsigned int sw_cpu2cfg_x2h_rst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2CFG_X2H_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2cfg_x2x_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2CFG_X2X_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2aon_x2h_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2AON_X2H_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_axi4_cpusys1_arst_n : 1; // [0]
        unsigned int sw_axi4_cpusys1_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AXI4_CPUSYS1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_aon2cpu_a2x_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_AON2CPU_A2X_TEESWRST_U;

typedef union {
    struct {
        unsigned int reserved_reg_1 : 32; // [31:0]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RESERVED_REG_1_TEE_U;

typedef union {
    struct {
        unsigned int reserved_reg_2 : 32; // [31:0]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RESERVED_REG_2_TEE_U;

typedef union {
    struct {
        unsigned int reserved_reg_3 : 32; // [31:0]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RESERVED_REG_3_TEE_U;

typedef union {
    struct {
        unsigned int reserved_reg_4 : 32; // [31:0]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RESERVED_REG_4_TEE_U;

typedef union {
    struct {
        unsigned int sw_npusys_axi_arst_n : 1; // [0]
        unsigned int sw_npusys_axi_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_NPUSYS_AXI_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2vp_x2p_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2VP_X2P_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_cpu2vi_x2h_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CPU2VI_X2H_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_bmu_c910_arst_n : 1; // [0]
        unsigned int sw_bmu_c910_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_BMU_C910_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_dmac_cpusys_arst_n : 1; // [0]
        unsigned int sw_dmac_cpusys_hrst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_DMAC_CPUSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_spinlock_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_SPINLOCK_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_cfg2tee_x2h_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_CFG2TEE_X2H_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_dsmart_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_DSMART_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_gpio3_dbrst_n : 1; // [0]
        unsigned int sw_gpio3_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GPIO3_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_i2s_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_I2S_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_img_nna_rst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_IMG_NNA_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_peri_apb3_hrst_n : 1; // [0]
        unsigned int sw_peri2peri1_apb_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERI_APB3_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_vp_subsys_prst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_VP_SUBSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_perisys_apb4_hrst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PERISYS_APB4_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_gmac1_prst_n : 1; // [0]
        unsigned int sw_gmac1_hrst_n : 1; // [1]
        unsigned int sw_gmac1_grst_n : 1; // [2]
        unsigned int sw_gmac1_arst_n : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GMAC1_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_gmac_axi_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_GMAC_AXI_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_padctrl1_apsys_prst_n : 1; // [0]
        unsigned int sw_gmac_axi_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_PADCTRL1_APSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_vosys_axi_arst_n : 1; // [0]
        unsigned int sw_vosys_axi_prst_n : 1; // [1]
        unsigned int RESERVED_0 : 30; // [31:2]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_VOSYS_AXI_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_vobus2npubus_x2x_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_VOSYS_X2X_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_misc2vp_x2x_arst_n : 1; // [0]
        unsigned int RESERVED_0 : 31; // [31:1]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_MISC2VP_X2X_TEESWRST_U;

typedef union {
    struct {
        unsigned int dsp_subsys_rst_n : 1; // [0]
        unsigned int vi_subsys_rst_n : 1; // [1]
        unsigned int vo_subsys_rst_n : 1; // [2]
        unsigned int vp_subsys_rst_n : 1; // [3]
        unsigned int RESERVED_0 : 28; // [31:4]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_SUBSYS_TEESWRST_U;

typedef union {
    struct {
        unsigned int sw_iopmp_aon_arst_n : 1; // [0]
        unsigned int sw_iopmp_aon_prst_n : 1; // [1]
        unsigned int sw_iopmp_aud_arst_n : 1; // [2]
        unsigned int sw_iopmp_aud_prst_n : 1; // [3]
        unsigned int sw_iopmp_chip_dbg_arst_n : 1; // [4]
        unsigned int sw_iopmp_chip_dbg_prst_n : 1; // [5]
        unsigned int sw_iopmp_dmac_cpusys_arst_n : 1; // [6]
        unsigned int sw_iopmp_dmac_cpusys_prst_n : 1; // [7]
        unsigned int RESERVED_2 : 8; // [15:8]
        unsigned int sw_iopmp_gmac0_arst_n : 1; // [16]
        unsigned int sw_iopmp_gmac0_prst_n : 1; // [17]
        unsigned int sw_iopmp_gmac1_arst_n : 1; // [18]
        unsigned int sw_iopmp_gmac1_prst_n : 1; // [19]
        unsigned int RESERVED_1 : 8; // [27:20]
        unsigned int sw_iopmp_npu_prst_n : 1; // [28]
        unsigned int RESERVED_0 : 3; // [31:29]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_IOPMP_TEESWRST_U;

typedef union {
    struct {
        unsigned int c910_brom_rst_lock : 1; // [0]
        unsigned int c910_core3_rst_lcok : 1; // [1]
        unsigned int c910_core2_rst_lcok : 1; // [2]
        unsigned int c910_core1_rst_lcok : 1; // [3]
        unsigned int c910_core0_rst_lcok : 1; // [4]
        unsigned int c910_rst_lock : 1; // [5]
        unsigned int chip_dbg_rst_lock : 1; // [6]
        unsigned int axi4_cpusys2_rst_lock : 1; // [7]
        unsigned int x2x_cpusys_rst_lock : 1; // [8]
        unsigned int x2h_cpusys_rst_lock : 1; // [9]
        unsigned int ahb2_cpusys_rst_lock : 1; // [10]
        unsigned int apb3_cpusys_rst_lock : 1; // [11]
        unsigned int mbox0_rst_lock : 1; // [12]
        unsigned int mbox1_rst_lock : 1; // [13]
        unsigned int mbox2_rst_lock : 1; // [14]
        unsigned int mbox3_rst_lock : 1; // [15]
        unsigned int wdt0_rst_lock : 1; // [16]
        unsigned int wdt1_rst_lock : 1; // [17]
        unsigned int timer0_rst_lock : 1; // [18]
        unsigned int timer1_rst_lock : 1; // [19]
        unsigned int perisys_ahb_rst_lock : 1; // [20]
        unsigned int perisys_apb1_rst_lock : 1; // [21]
        unsigned int perisys_apb2_rst_lock : 1; // [22]
        unsigned int perisys_axi_rst_lock : 1; // [23]
        unsigned int gmac0_rst_lock : 1; // [24]
        unsigned int usb3_drd_lock : 1; // [25]
        unsigned int uart0_rst_lock : 1; // [26]
        unsigned int uart1_rst_lock : 1; // [27]
        unsigned int uart2_rst_lock : 1; // [28]
        unsigned int uart3_rst_lock : 1; // [29]
        unsigned int uart4_rst_lock : 1; // [30]
        unsigned int uart5_rst_lock : 1; // [31]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RST_LOCK_0_U;

typedef union {
    struct {
        unsigned int qspi0_rst_lock : 1; // [0]
        unsigned int qspi1_rst_lock : 1; // [1]
        unsigned int spi_rst_lock : 1; // [2]
        unsigned int i2c0_rst_lock : 1; // [3]
        unsigned int i2c1_rst_lock : 1; // [4]
        unsigned int i2c2_rst_lock : 1; // [5]
        unsigned int i2c3_rst_lock : 1; // [6]
        unsigned int i2c4_rst_lock : 1; // [7]
        unsigned int i2c5_rst_lock : 1; // [8]
        unsigned int gpio0_rst_lock : 1; // [9]
        unsigned int gpio1_rst_lock : 1; // [10]
        unsigned int gpio2_rst_lock : 1; // [11]
        unsigned int RESERVED_3 : 1; // [12]
        unsigned int pwm_rst_lock : 1; // [13]
        unsigned int padctrl0_apsys_rst_lock : 1; // [14]
        unsigned int RESERVED_2 : 1; // [15]
        unsigned int cpu2peri_x2h_rst_lock : 1; // [16]
        unsigned int axi4_cfg_bus_rst_lock : 1; // [17]
        unsigned int cpu2cfg_x2h_rst_lock : 1; // [18]
        unsigned int cpu2cfg_apb_rst_lock : 1; // [19]
        unsigned int cpu2cfg_x2x_rst_lock : 1; // [20]
        unsigned int cpu2aon_x2h_rst_lock : 1; // [21]
        unsigned int axi4_cpusys1_rst_lock : 1; // [22]
        unsigned int aon2cpu_a2x_rst_lock : 1; // [23]
        unsigned int reserved_reg_1_lock : 1; // [24]
        unsigned int reserved_reg_2_lock : 1; // [25]
        unsigned int reserved_reg_3_lock : 1; // [26]
        unsigned int reserved_reg_4_lock : 1; // [27]
        unsigned int RESERVED_1 : 1; // [28]
        unsigned int peri2ddr_x2x_rst_lock : 1; // [29]
        unsigned int RESERVED_0 : 1; // [30]
        unsigned int visys_axi_rst_lock : 1; // [31]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RST_LOCK_1_U;

typedef union {
    struct {
        unsigned int npusys_axi_rst_lock : 1; // [0]
        unsigned int cpu2vp_x2p_rst_lock : 1; // [1]
        unsigned int RESERVED_5 : 1; // [2]
        unsigned int cpu2vi_x2h_rst_lock : 1; // [3]
        unsigned int tee2ddr_x2x_rst_lock : 1; // [4]
        unsigned int npu2sram_x2x_rst_lock : 1; // [5]
        unsigned int bmu_c910_rst_lock : 1; // [6]
        unsigned int dmac_cpusys_rst_lock : 1; // [7]
        unsigned int RESERVED_4 : 6; // [13:8]
        unsigned int sdio0_rst_lock : 1; // [14]
        unsigned int RESERVED_3 : 1; // [15]
        unsigned int sdio1_rst_lock : 1; // [16]
        unsigned int RESERVED_2 : 1; // [17]
        unsigned int spinlock_rst_lock : 1; // [18]
        unsigned int RESERVED_1 : 2; // [20:19]
        unsigned int cfg2tee_x2h_rst_lock : 1; // [21]
        unsigned int dsmart_rst_lock : 1; // [22]
        unsigned int RESERVED_0 : 4; // [26:23]
        unsigned int emmc_rst_lock : 1; // [27]
        unsigned int emmc_x2x_rst_lock : 1; // [28]
        unsigned int gpio3_rst_lock : 1; // [29]
        unsigned int i2s_rst_lock : 1; // [30]
        unsigned int img_nna_rst_lock : 1; // [31]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RST_LOCK_2_U;

typedef union {
    struct {
        unsigned int RESERVED_5 : 9; // [8:0]
        unsigned int peri_apb3_rst_lock : 1; // [9]
        unsigned int peri2peri1_apb_rst_lock : 1; // [10]
        unsigned int RESERVED_4 : 2; // [12:11]
        unsigned int vp_subsys_rst_lock : 1; // [13]
        unsigned int gpio4_rst_lock : 1; // [14]
        unsigned int RESERVED_3 : 1; // [15]
        unsigned int perisys_apb4_lock : 1; // [16]
        unsigned int RESERVED_2 : 1; // [17]
        unsigned int gmac1_rst_lock : 1; // [18]
        unsigned int RESERVED_1 : 2; // [20:19]
        unsigned int padctrl1_apsys_rst_lock : 1; // [21]
        unsigned int gmac_axi_rst_lock : 1; // [22]
        unsigned int vobus2npubus_x2x_arst_lock : 1; // [23]
        unsigned int vosys_axi_arst_lock : 1; // [24]
        unsigned int misc2vp_x2x_arst_lock : 1; // [25]
        unsigned int dspsys_rst_lock : 1; // [26]
        unsigned int visys_rst_lock : 1; // [27]
        unsigned int vosys_rst_lock : 1; // [28]
        unsigned int RESERVED_0 : 3; // [31:29]
    };
    unsigned int u32;
} APSYS_RSTGEN_REG_SW_RST_LOCK_3_U;

typedef union {
    volatile APSYS_RSTGEN_REG_SW_C910_BROM_SWRST_U apsys_rstgen_reg_sw_c910_brom_swrst;    // 0x0
    volatile APSYS_RSTGEN_REG_SW_C910_SWRST_U apsys_rstgen_reg_sw_c910_swrst;    // 0x4
    volatile APSYS_RSTGEN_REG_SW_CHIP_DBG_SWRST_U apsys_rstgen_reg_sw_chip_dbg_swrst;    // 0xc
    volatile APSYS_RSTGEN_REG_SW_AXI4_CPUSYS2_SWRST_U apsys_rstgen_reg_sw_axi4_cpusys2_swrst;    // 0x10
    volatile APSYS_RSTGEN_REG_SW_X2X_CPUSYS_SWRST_U apsys_rstgen_reg_sw_x2x_cpusys_swrst;    // 0x14
    volatile APSYS_RSTGEN_REG_SW_X2H_CPUSYS_SWRST_U apsys_rstgen_reg_sw_x2h_cpusys_swrst;    // 0x18
    volatile APSYS_RSTGEN_REG_SW_AHB2_CPUSYS_SWRST_U apsys_rstgen_reg_sw_ahb2_cpusys_swrst;    // 0x1c
    volatile APSYS_RSTGEN_REG_SW_APB3_CPUSYS_SWRST_U apsys_rstgen_reg_sw_apb3_cpusys_swrst;    // 0x20
    volatile APSYS_RSTGEN_REG_SW_MBOX0_SWRST_U apsys_rstgen_reg_sw_mbox0_swrst;    // 0x24
    volatile APSYS_RSTGEN_REG_SW_MBOX1_SWRST_U apsys_rstgen_reg_sw_mbox1_swrst;    // 0x28
    volatile APSYS_RSTGEN_REG_SW_MBOX2_SWRST_U apsys_rstgen_reg_sw_mbox2_swrst;    // 0x2c
    volatile APSYS_RSTGEN_REG_SW_MBOX3_SWRST_U apsys_rstgen_reg_sw_mbox3_swrst;    // 0x30
    volatile APSYS_RSTGEN_REG_SW_WDT0_SWRST_U apsys_rstgen_reg_sw_wdt0_swrst;    // 0x34
    volatile APSYS_RSTGEN_REG_SW_WDT1_SWRST_U apsys_rstgen_reg_sw_wdt1_swrst;    // 0x38
    volatile APSYS_RSTGEN_REG_SW_TIMER0_SWRST_U apsys_rstgen_reg_sw_timer0_swrst;    // 0x3c
    volatile APSYS_RSTGEN_REG_SW_TIMER1_SWRST_U apsys_rstgen_reg_sw_timer1_swrst;    // 0x40
    volatile APSYS_RSTGEN_REG_SW_PERISYS_AHB_SWRST_U apsys_rstgen_reg_sw_perisys_ahb_swrst;    // 0x44
    volatile APSYS_RSTGEN_REG_SW_PERISYS_APB1_SWRST_U apsys_rstgen_reg_sw_perisys_apb1_swrst;    // 0x48
    volatile APSYS_RSTGEN_REG_SW_PERISYS_APB2_SWRST_U apsys_rstgen_reg_sw_perisys_apb2_swrst;    // 0x4c
    volatile APSYS_RSTGEN_REG_SW_GMAC0_SWRST_U apsys_rstgen_reg_sw_gmac0_swrst;    // 0x68
   volatile APSYS_RSTGEN_REG_SW_UART0_SWRST_U apsys_rstgen_reg_sw_uart0_swrst;    // 0x70
    volatile APSYS_RSTGEN_REG_SW_UART1_SWRST_U apsys_rstgen_reg_sw_uart1_swrst;    // 0x74
    volatile APSYS_RSTGEN_REG_SW_UART2_SWRST_U apsys_rstgen_reg_sw_uart2_swrst;    // 0x78
    volatile APSYS_RSTGEN_REG_SW_UART3_SWRST_U apsys_rstgen_reg_sw_uart3_swrst;    // 0x7c
    volatile APSYS_RSTGEN_REG_SW_UART4_SWRST_U apsys_rstgen_reg_sw_uart4_swrst;    // 0x80
    volatile APSYS_RSTGEN_REG_SW_UART5_SWRST_U apsys_rstgen_reg_sw_uart5_swrst;    // 0x84
    volatile APSYS_RSTGEN_REG_SW_QSPI0_SWRST_U apsys_rstgen_reg_sw_qspi0_swrst;    // 0x8c
    volatile APSYS_RSTGEN_REG_SW_QSPI1_SWRST_U apsys_rstgen_reg_sw_qspi1_swrst;    // 0x90
    volatile APSYS_RSTGEN_REG_SW_SPI_SWRST_U apsys_rstgen_reg_sw_spi_swrst;    // 0x94
    volatile APSYS_RSTGEN_REG_SW_I2C0_SWRST_U apsys_rstgen_reg_sw_i2c0_swrst;    // 0x98
    volatile APSYS_RSTGEN_REG_SW_I2C1_SWRST_U apsys_rstgen_reg_sw_i2c1_swrst;    // 0x9c
    volatile APSYS_RSTGEN_REG_SW_I2C2_SWRST_U apsys_rstgen_reg_sw_i2c2_swrst;    // 0xa0
    volatile APSYS_RSTGEN_REG_SW_I2C3_SWRST_U apsys_rstgen_reg_sw_i2c3_swrst;    // 0xa4
    volatile APSYS_RSTGEN_REG_SW_I2C4_SWRST_U apsys_rstgen_reg_sw_i2c4_swrst;    // 0xa8
    volatile APSYS_RSTGEN_REG_SW_I2C5_SWRST_U apsys_rstgen_reg_sw_i2c5_swrst;    // 0xac
    volatile APSYS_RSTGEN_REG_SW_GPIO0_SWRST_U apsys_rstgen_reg_sw_gpio0_swrst;    // 0xb0
    volatile APSYS_RSTGEN_REG_SW_GPIO1_SWRST_U apsys_rstgen_reg_sw_gpio1_swrst;    // 0xb4
    volatile APSYS_RSTGEN_REG_SW_GPIO2_SWRST_U apsys_rstgen_reg_sw_gpio2_swrst;    // 0xb8
    volatile APSYS_RSTGEN_REG_SW_PWM_SWRST_U apsys_rstgen_reg_sw_pwm_swrst;    // 0xc0
    volatile APSYS_RSTGEN_REG_SW_PADCTRL0_APSYS_SWRST_U apsys_rstgen_reg_sw_padctrl0_apsys_swrst;    // 0xc4
    volatile APSYS_RSTGEN_REG_SW_CPU2PERI_X2H_SWRST_U apsys_rstgen_reg_sw_cpu2peri_x2h_swrst;    // 0xcc
    volatile APSYS_RSTGEN_REG_SW_AXI4_CFG_BUS_SWRST_U apsys_rstgen_reg_sw_axi4_cfg_bus_swrst;    // 0xd4
    volatile APSYS_RSTGEN_REG_SW_CPU2CFG_X2H_SWRST_U apsys_rstgen_reg_sw_cpu2cfg_x2h_swrst;    // 0xd8
    volatile APSYS_RSTGEN_REG_SW_CPU2CFG_X2X_SWRST_U apsys_rstgen_reg_sw_cpu2cfg_x2x_swrst;    // 0xdc
    volatile APSYS_RSTGEN_REG_SW_CPU2AON_X2H_SWRST_U apsys_rstgen_reg_sw_cpu2aon_x2h_swrst;    // 0xe4
    volatile APSYS_RSTGEN_REG_SW_AXI4_CPUSYS1_SWRST_U apsys_rstgen_reg_sw_axi4_cpusys1_swrst;    // 0xf8
    volatile APSYS_RSTGEN_REG_SW_AON2CPU_A2X_SWRST_U apsys_rstgen_reg_sw_aon2cpu_a2x_swrst;    // 0xfc
    volatile APSYS_RSTGEN_REG_SW_RESERVED_REG_1_U apsys_rstgen_reg_sw_reserved_reg_1;    // 0x100
    volatile APSYS_RSTGEN_REG_SW_RESERVED_REG_2_U apsys_rstgen_reg_sw_reserved_reg_2;    // 0x104
    volatile APSYS_RSTGEN_REG_SW_RESERVED_REG_3_U apsys_rstgen_reg_sw_reserved_reg_3;    // 0x108
    volatile APSYS_RSTGEN_REG_SW_RESERVED_REG_4_U apsys_rstgen_reg_sw_reserved_reg_4;    // 0x10c
    volatile APSYS_RSTGEN_REG_SW_NPUSYS_AXI_SWRST_U apsys_rstgen_reg_sw_npusys_axi_swrst;    // 0x128
    volatile APSYS_RSTGEN_REG_SW_CPU2VP_X2P_SWRST_U apsys_rstgen_reg_sw_cpu2vp_x2p_swrst;    // 0x12c
    volatile APSYS_RSTGEN_REG_SW_CPU2VI_X2H_SWRST_U apsys_rstgen_reg_sw_cpu2vi_x2h_swrst;    // 0x138
    volatile APSYS_RSTGEN_REG_SW_BMU_C910_SWRST_U apsys_rstgen_reg_sw_bmu_c910_swrst;    // 0x148
    volatile APSYS_RSTGEN_REG_SW_DMAC_CPUSYS_SWRST_U apsys_rstgen_reg_sw_dmac_cpusys_swrst;    // 0x14c
    volatile APSYS_RSTGEN_REG_SW_SPINLOCK_SWRST_U apsys_rstgen_reg_sw_spinlock_swrst;    // 0x178
    volatile APSYS_RSTGEN_REG_SW_CFG2TEE_X2H_SWRST_U apsys_rstgen_reg_sw_cfg2tee_x2h_swrst;    // 0x188
    volatile APSYS_RSTGEN_REG_SW_DSMART_SWRST_U apsys_rstgen_reg_sw_dsmart_swrst;    // 0x18c
    volatile APSYS_RSTGEN_REG_SW_GPIO3_SWRST_U apsys_rstgen_reg_sw_gpio3_swrst;    // 0x1a8
    volatile APSYS_RSTGEN_REG_SW_I2S_SWRST_U apsys_rstgen_reg_sw_i2s_swrst;    // 0x1ac
    volatile APSYS_RSTGEN_REG_SW_IMG_NNA_SWRST_U apsys_rstgen_reg_sw_img_nna_swrst;    // 0x1b0
    volatile APSYS_RSTGEN_REG_SW_PERI_APB3_SWRST_U apsys_rstgen_reg_sw_peri_apb3_swrst;    // 0x1dc
    volatile APSYS_RSTGEN_REG_SW_VP_SUBSYS_SWRST_U apsys_rstgen_reg_sw_vp_subsys_swrst;    // 0x1ec
    volatile APSYS_RSTGEN_REG_SW_PERISYS_APB4_SWRST_U apsys_rstgen_reg_sw_perisys_apb4_swrst;    // 0x1f8
    volatile APSYS_RSTGEN_REG_SW_GMAC1_SWRST_U apsys_rstgen_reg_sw_gmac1_swrst;    // 0x204
    volatile APSYS_RSTGEN_REG_SW_GMAC_AXI_SWRST_U apsys_rstgen_reg_sw_gmac_axi_swrst;    // 0x208
    volatile APSYS_RSTGEN_REG_SW_PADCTRL1_APSYS_SWRST_U apsys_rstgen_reg_sw_padctrl1_apsys_swrst;    // 0x20c
    volatile APSYS_RSTGEN_REG_SW_VOSYS_AXI_SWRST_U apsys_rstgen_reg_sw_vosys_axi_swrst;    // 0x210
    volatile APSYS_RSTGEN_REG_SW_VOSYS_X2X_SWRST_U apsys_rstgen_reg_sw_vosys_x2x_swrst;    // 0x214
   volatile APSYS_RSTGEN_REG_SW_MISC2VP_X2X_SWRST_U apsys_rstgen_reg_sw_misc2vp_x2x_swrst;    // 0x218
    volatile APSYS_RSTGEN_REG_SW_SUBSYS_SWRST_U apsys_rstgen_reg_sw_subsys_swrst;    // 0x220
    volatile APSYS_RSTGEN_REG_SW_C910_BROM_TEESWRST_U apsys_rstgen_reg_sw_c910_brom_teeswrst;    // 0x1000
    volatile APSYS_RSTGEN_REG_SW_C910_TEESWRST_U apsys_rstgen_reg_sw_c910_teeswrst;    // 0x1004
    volatile APSYS_RSTGEN_REG_SW_C910_DS_TEESWRST_U apsys_rstgen_reg_sw_c910_ds_teeswrst;    // 0x1008
    volatile APSYS_RSTGEN_REG_SW_CHIP_DBG_TEESWRST_U apsys_rstgen_reg_sw_chip_dbg_teeswrst;    // 0x100c
    volatile APSYS_RSTGEN_REG_SW_AXI4_CPUSYS2_TEESWRST_U apsys_rstgen_reg_sw_axi4_cpusys2_teeswrst;    // 0x1010
    volatile APSYS_RSTGEN_REG_SW_X2X_CPUSYS_TEESWRST_U apsys_rstgen_reg_sw_x2x_cpusys_teeswrst;    // 0x1014
    volatile APSYS_RSTGEN_REG_SW_X2H_CPUSYS_TEESWRST_U apsys_rstgen_reg_sw_x2h_cpusys_teeswrst;    // 0x1018
    volatile APSYS_RSTGEN_REG_SW_AHB2_CPUSYS_TEESWRST_U apsys_rstgen_reg_sw_ahb2_cpusys_teeswrst;    // 0x101c
    volatile APSYS_RSTGEN_REG_SW_APB3_CPUSYS_TEESWRST_U apsys_rstgen_reg_sw_apb3_cpusys_teeswrst;    // 0x1020
    volatile APSYS_RSTGEN_REG_SW_MBOX0_TEESWRST_U apsys_rstgen_reg_sw_mbox0_teeswrst;    // 0x1024
    volatile APSYS_RSTGEN_REG_SW_MBOX1_TEESWRST_U apsys_rstgen_reg_sw_mbox1_teeswrst;    // 0x1028
    volatile APSYS_RSTGEN_REG_SW_MBOX2_TEESWRST_U apsys_rstgen_reg_sw_mbox2_teeswrst;    // 0x102c
    volatile APSYS_RSTGEN_REG_SW_MBOX3_TEESWRST_U apsys_rstgen_reg_sw_mbox3_teeswrst;    // 0x1030
    volatile APSYS_RSTGEN_REG_SW_WDT0_TEESWRST_U apsys_rstgen_reg_sw_wdt0_teeswrst;    // 0x1034
    volatile APSYS_RSTGEN_REG_SW_WDT1_TEESWRST_U apsys_rstgen_reg_sw_wdt1_teeswrst;    // 0x1038
    volatile APSYS_RSTGEN_REG_SW_TIMER0_TEESWRST_U apsys_rstgen_reg_sw_timer0_teeswrst;    // 0x103c
    volatile APSYS_RSTGEN_REG_SW_TIMER1_TEESWRST_U apsys_rstgen_reg_sw_timer1_teeswrst;    // 0x1040
    volatile APSYS_RSTGEN_REG_SW_PERISYS_AHB_TEESWRST_U apsys_rstgen_reg_sw_perisys_ahb_teeswrst;    // 0x1044
    volatile APSYS_RSTGEN_REG_SW_PERISYS_APB1_TEESWRST_U apsys_rstgen_reg_sw_perisys_apb1_teeswrst;    // 0x1048
    volatile APSYS_RSTGEN_REG_SW_PERISYS_APB2_TEESWRST_U apsys_rstgen_reg_sw_perisys_apb2_teeswrst;    // 0x104c
    volatile APSYS_RSTGEN_REG_SW_GMAC0_TEESWRST_U apsys_rstgen_reg_sw_gmac0_teeswrst;    // 0x1068
    volatile APSYS_RSTGEN_REG_SW_UART0_TEESWRST_U apsys_rstgen_reg_sw_uart0_teeswrst;    // 0x1070
    volatile APSYS_RSTGEN_REG_SW_UART1_TEESWRST_U apsys_rstgen_reg_sw_uart1_teeswrst;    // 0x1074
    volatile APSYS_RSTGEN_REG_SW_UART2_TEESWRST_U apsys_rstgen_reg_sw_uart2_teeswrst;    // 0x1078
    volatile APSYS_RSTGEN_REG_SW_UART3_TEESWRST_U apsys_rstgen_reg_sw_uart3_teeswrst;    // 0x107c
    volatile APSYS_RSTGEN_REG_SW_UART4_TEESWRST_U apsys_rstgen_reg_sw_uart4_teeswrst;    // 0x1080
    volatile APSYS_RSTGEN_REG_SW_UART5_TEESWRST_U apsys_rstgen_reg_sw_uart5_teeswrst;    // 0x1084
    volatile APSYS_RSTGEN_REG_SW_QSPI0_TEESWRST_U apsys_rstgen_reg_sw_qspi0_teeswrst;    // 0x108c
    volatile APSYS_RSTGEN_REG_SW_QSPI1_TEESWRST_U apsys_rstgen_reg_sw_qspi1_teeswrst;    // 0x1090
    volatile APSYS_RSTGEN_REG_SW_SPI_TEESWRST_U apsys_rstgen_reg_sw_spi_teeswrst;    // 0x1094
    volatile APSYS_RSTGEN_REG_SW_I2C0_TEESWRST_U apsys_rstgen_reg_sw_i2c0_teeswrst;    // 0x1098
    volatile APSYS_RSTGEN_REG_SW_I2C1_TEESWRST_U apsys_rstgen_reg_sw_i2c1_teeswrst;    // 0x109c
    volatile APSYS_RSTGEN_REG_SW_I2C2_TEESWRST_U apsys_rstgen_reg_sw_i2c2_teeswrst;    // 0x10a0
    volatile APSYS_RSTGEN_REG_SW_I2C3_TEESWRST_U apsys_rstgen_reg_sw_i2c3_teeswrst;    // 0x10a4
    volatile APSYS_RSTGEN_REG_SW_I2C4_TEESWRST_U apsys_rstgen_reg_sw_i2c4_teeswrst;    // 0x10a8
    volatile APSYS_RSTGEN_REG_SW_I2C5_TEESWRST_U apsys_rstgen_reg_sw_i2c5_teeswrst;    // 0x10ac
    volatile APSYS_RSTGEN_REG_SW_GPIO0_TEESWRST_U apsys_rstgen_reg_sw_gpio0_teeswrst;    // 0x10b0
    volatile APSYS_RSTGEN_REG_SW_GPIO1_TEESWRST_U apsys_rstgen_reg_sw_gpio1_teeswrst;    // 0x10b4
    volatile APSYS_RSTGEN_REG_SW_GPIO2_TEESWRST_U apsys_rstgen_reg_sw_gpio2_teeswrst;    // 0x10b8
    volatile APSYS_RSTGEN_REG_SW_PWM_TEESWRST_U apsys_rstgen_reg_sw_pwm_teeswrst;    // 0x10c0
    volatile APSYS_RSTGEN_REG_SW_PADCTRL0_APSYS_TEESWRST_U apsys_rstgen_reg_sw_padctrl0_apsys_teeswrst;    // 0x10c4
   volatile APSYS_RSTGEN_REG_SW_CPU2PERI_X2H_TEESWRST_U apsys_rstgen_reg_sw_cpu2peri_x2h_teeswrst;    // 0x10cc
    volatile APSYS_RSTGEN_REG_SW_AXI4_CFG_BUS_TEESWRST_U apsys_rstgen_reg_sw_axi4_cfg_bus_teeswrst;    // 0x10d4
    volatile APSYS_RSTGEN_REG_SW_CPU2CFG_X2H_TEESWRST_U apsys_rstgen_reg_sw_cpu2cfg_x2h_teeswrst;    // 0x10d8
    volatile APSYS_RSTGEN_REG_SW_CPU2CFG_X2X_TEESWRST_U apsys_rstgen_reg_sw_cpu2cfg_x2x_teeswrst;    // 0x10dc
    volatile APSYS_RSTGEN_REG_SW_CPU2AON_X2H_TEESWRST_U apsys_rstgen_reg_sw_cpu2aon_x2h_teeswrst;    // 0x10e4
    volatile APSYS_RSTGEN_REG_SW_AXI4_CPUSYS1_TEESWRST_U apsys_rstgen_reg_sw_axi4_cpusys1_teeswrst;    // 0x10f8
    volatile APSYS_RSTGEN_REG_SW_AON2CPU_A2X_TEESWRST_U apsys_rstgen_reg_sw_aon2cpu_a2x_teeswrst;    // 0x10fc
    volatile APSYS_RSTGEN_REG_SW_RESERVED_REG_1_TEE_U apsys_rstgen_reg_sw_reserved_reg_1_tee;    // 0x1100
    volatile APSYS_RSTGEN_REG_SW_RESERVED_REG_2_TEE_U apsys_rstgen_reg_sw_reserved_reg_2_tee;    // 0x1104
    volatile APSYS_RSTGEN_REG_SW_RESERVED_REG_3_TEE_U apsys_rstgen_reg_sw_reserved_reg_3_tee;    // 0x1108
    volatile APSYS_RSTGEN_REG_SW_RESERVED_REG_4_TEE_U apsys_rstgen_reg_sw_reserved_reg_4_tee;    // 0x110c
    volatile APSYS_RSTGEN_REG_SW_NPUSYS_AXI_TEESWRST_U apsys_rstgen_reg_sw_npusys_axi_teeswrst;    // 0x1128
    volatile APSYS_RSTGEN_REG_SW_CPU2VP_X2P_TEESWRST_U apsys_rstgen_reg_sw_cpu2vp_x2p_teeswrst;    // 0x112c
    volatile APSYS_RSTGEN_REG_SW_CPU2VI_X2H_TEESWRST_U apsys_rstgen_reg_sw_cpu2vi_x2h_teeswrst;    // 0x1138
    volatile APSYS_RSTGEN_REG_SW_BMU_C910_TEESWRST_U apsys_rstgen_reg_sw_bmu_c910_teeswrst;    // 0x1148
    volatile APSYS_RSTGEN_REG_SW_DMAC_CPUSYS_TEESWRST_U apsys_rstgen_reg_sw_dmac_cpusys_teeswrst;    // 0x114c
    volatile APSYS_RSTGEN_REG_SW_SPINLOCK_TEESWRST_U apsys_rstgen_reg_sw_spinlock_teeswrst;    // 0x1178
    volatile APSYS_RSTGEN_REG_SW_CFG2TEE_X2H_TEESWRST_U apsys_rstgen_reg_sw_cfg2tee_x2h_teeswrst;    // 0x1188
    volatile APSYS_RSTGEN_REG_SW_DSMART_TEESWRST_U apsys_rstgen_reg_sw_dsmart_teeswrst;    // 0x118c
    volatile APSYS_RSTGEN_REG_SW_GPIO3_TEESWRST_U apsys_rstgen_reg_sw_gpio3_teeswrst;    // 0x11a8
    volatile APSYS_RSTGEN_REG_SW_I2S_TEESWRST_U apsys_rstgen_reg_sw_i2s_teeswrst;    // 0x11ac
    volatile APSYS_RSTGEN_REG_SW_IMG_NNA_TEESWRST_U apsys_rstgen_reg_sw_img_nna_teeswrst;    // 0x11b0
    volatile APSYS_RSTGEN_REG_SW_PERI_APB3_TEESWRST_U apsys_rstgen_reg_sw_peri_apb3_teeswrst;    // 0x11dc
    volatile APSYS_RSTGEN_REG_SW_VP_SUBSYS_TEESWRST_U apsys_rstgen_reg_sw_vp_subsys_teeswrst;    // 0x11ec
    volatile APSYS_RSTGEN_REG_SW_PERISYS_APB4_TEESWRST_U apsys_rstgen_reg_sw_perisys_apb4_teeswrst;    // 0x11f8
    volatile APSYS_RSTGEN_REG_SW_GMAC1_TEESWRST_U apsys_rstgen_reg_sw_gmac1_teeswrst;    // 0x1204
    volatile APSYS_RSTGEN_REG_SW_GMAC_AXI_TEESWRST_U apsys_rstgen_reg_sw_gmac_axi_teeswrst;    // 0x1208
    volatile APSYS_RSTGEN_REG_SW_PADCTRL1_APSYS_TEESWRST_U apsys_rstgen_reg_sw_padctrl1_apsys_teeswrst;    // 0x120c
    volatile APSYS_RSTGEN_REG_SW_VOSYS_AXI_TEESWRST_U apsys_rstgen_reg_sw_vosys_axi_teeswrst;    // 0x1210
    volatile APSYS_RSTGEN_REG_SW_VOSYS_X2X_TEESWRST_U apsys_rstgen_reg_sw_vosys_x2x_teeswrst;    // 0x1214
    volatile APSYS_RSTGEN_REG_SW_MISC2VP_X2X_TEESWRST_U apsys_rstgen_reg_sw_misc2vp_x2x_teeswrst;    // 0x1218
    volatile APSYS_RSTGEN_REG_SW_SUBSYS_TEESWRST_U apsys_rstgen_reg_sw_subsys_teeswrst;    // 0x1220
    volatile APSYS_RSTGEN_REG_SW_IOPMP_TEESWRST_U apsys_rstgen_reg_sw_iopmp_teeswrst;    // 0x1500
    volatile APSYS_RSTGEN_REG_SW_RST_LOCK_0_U apsys_rstgen_reg_sw_rst_lock_0;    // 0x1800
    volatile APSYS_RSTGEN_REG_SW_RST_LOCK_1_U apsys_rstgen_reg_sw_rst_lock_1;    // 0x1804
    volatile APSYS_RSTGEN_REG_SW_RST_LOCK_2_U apsys_rstgen_reg_sw_rst_lock_2;    // 0x1808
    volatile APSYS_RSTGEN_REG_SW_RST_LOCK_3_U apsys_rstgen_reg_sw_rst_lock_3;    // 0x180c
} APSYS_RSTGEN_REG_SW_REG_S;

#endif