#ifndef MISCSYS_SYSREG_REG_OFFSET_DEFINE_H
#define MISCSYS_SYSREG_REG_OFFSET_DEFINE_H

#define REG_MISC_SYSREG_REE_BASE		0xBC02C000
#define REG_MISC_SYSREG_TEE_BASE		0xFC02C000

#define REG_MISCSYS_SDIO0_CLK_CTRL		(REG_MISC_SYSREG_REE_BASE + 0x10c)
#define REG_MISCSYS_SDIO1_CLK_CTRL		(REG_MISC_SYSREG_REE_BASE + 0x110)

#define SDIO_CLK_EN						(1 << 0)

#endif
