#ifndef VISYS_SYSREG_REG_OFFSET_DEFINE_H
#define VISYS_SYSREG_REG_OFFSET_DEFINE_H

#define REG_VI_SYSREG_REE_BASE		0xB4040000
#define REG_VI_SYSREG_TEE_BASE		0xF4040000

#define REG_VI_VISYS_CLK_GATE_EN_0		(REG_VI_SYSREG_REE_BASE + 0xa0)
#define REG_VI_VISYS_CLK_GATE_EN_1		(REG_VI_SYSREG_REE_BASE + 0xa4)

#define VISYS_CLKCTRL_ISP_RY_CCLK_EN		(1 << 21)
#define VISYS_CLKCTRL_ISP_RY_ACLK_EN		(1 << 22)
#define VISYS_CLKCTRL_ISP_RY_HCLK_EN		(1 << 12)
#define VISYS_CLKCTRL_ISP1_CLK_EN			(1 << 30)
#define VISYS_CLKCTRL_ISP0_CLK_EN			(1 << 31)

#endif
