/*
 * Copyright (C) 2017-2019 Alibaba Group Holding Limited
 */

 /******************************************************************************
 * @file     startup.S
 * @brief    startup file for DANICA. Should use with
 *           GCC for CSKY Embedded Processors
 * @version  V1.0
 * @date     05. July 2018
 ******************************************************************************/

#include <csi_config.h>

To do
