#ifndef MSH8_DRIVER__H
#define MSH8_DRIVER__H

#include "common_lib.h"
#include "MSH8_regmodel.h"

#define FIFO_DEPTH          512
#define FIFO_WIDTH          64
//#define EMMC_MSH8_BADDR     0xFFE7090000
#define EMMC_MSH8_BADDR     0xFFE7080000
#define EMMC_RCA_ARG        0x000000000
#define EMMC_DDR_BADDR      0x0000000000
#define EMMC_CLKGEN_BADDR   0xFFEF010000
#define EMMC_CLKGEN_OFFSET  0x200
#define EMMC_CLKGEN_VALUE   0xFFFFFFFF
#define EMMC_RSTGEN_BADDR   0xFFEF014000
#define EMMC_RSTGEN_OFFSET  0x064
#define EMMC_RSTGEN_VALUE   0x1

DWC_MSH8_REGMODEL_REG_S     EMMC_REG;


#ifdef EMMC_MULTI_BLOCK_XFER
    //Descriptor for write
    #define  EMMC_FIRST_W_DESCRIPTOR_ADDR        EMMC_DDR_BADDR + 0x400
    #define  EMMC_SECOND_W_DESCRIPTOR_ADDR       EMMC_DDR_BADDR + 0x800
    #define  EMMC_FIRST_W_DATABUFFER1_ADDR       EMMC_DDR_BADDR + 0x2000
    #define  EMMC_FIRST_W_DATABUFFER2_ADDR       EMMC_DDR_BADDR + 0x3000
    #define  EMMC_FIRST_W_DATABUFFER3_ADDR       EMMC_DDR_BADDR + 0x4000
    #define  EMMC_FIRST_W_DATABUFFER4_ADDR       EMMC_DDR_BADDR + 0x5000
    #define  EMMC_SECOND_W_DATABUFFER1_ADDR      EMMC_DDR_BADDR + 0x6000
    #define  EMMC_SECOND_W_DATABUFFER2_ADDR      EMMC_DDR_BADDR + 0x7000
    #define  EMMC_SECOND_W_DATABUFFER3_ADDR      EMMC_DDR_BADDR + 0x8000
    #define  EMMC_SECOND_W_DATABUFFER4_ADDR      EMMC_DDR_BADDR + 0x9000
    //Descriptor for read
    #define  EMMC_FIRST_R_DESCRIPTOR_ADDR        EMMC_DDR_BADDR + 0x10400
    #define  EMMC_SECOND_R_DESCRIPTOR_ADDR       EMMC_DDR_BADDR + 0x10800
    #define  EMMC_FIRST_R_DATABUFFER1_ADDR       EMMC_DDR_BADDR + 0x12000
    #define  EMMC_FIRST_R_DATABUFFER2_ADDR       EMMC_DDR_BADDR + 0x13000
    #define  EMMC_FIRST_R_DATABUFFER3_ADDR       EMMC_DDR_BADDR + 0x14000
    #define  EMMC_FIRST_R_DATABUFFER4_ADDR       EMMC_DDR_BADDR + 0x15000
    #define  EMMC_SECOND_R_DATABUFFER1_ADDR      EMMC_DDR_BADDR + 0x16000
    #define  EMMC_SECOND_R_DATABUFFER2_ADDR      EMMC_DDR_BADDR + 0x17000
    #define  EMMC_SECOND_R_DATABUFFER3_ADDR      EMMC_DDR_BADDR + 0x18000
    #define  EMMC_SECOND_R_DATABUFFER4_ADDR      EMMC_DDR_BADDR + 0x19000

    #define  FLAG_FOR_SCOREBOARD_MULTI           0x80

#elif EMMC_SINGLE_BLOCK_XFER
    //Descriptor for write
    #define  EMMC_FIRST_W_DESCRIPTOR_ADDR        EMMC_DDR_BADDR + 0x400
    #define  EMMC_FIRST_W_DATABUFFER1_ADDR       EMMC_DDR_BADDR + 0x2000
    //Descriptor for read
    #define  EMMC_FIRST_R_DESCRIPTOR_ADDR        EMMC_DDR_BADDR + 0x10400
    #define  EMMC_FIRST_R_DATABUFFER1_ADDR       EMMC_DDR_BADDR + 0x12000

    #define  FLAG_FOR_SCOREBOARD_SINGLE          0xf0

#elif EMMC_BOOT_XFER
    #define  EMMC_FIRST_W_DATABUFFER1_ADDR       EMMC_DDR_BADDR + 0x2000
    #define  EMMC_FIRST_R_DATABUFFER1_ADDR       EMMC_DDR_BADDR + 0x12000

    #define  FLAG_FOR_BOOT                       0x20
    #define  FLAG_FOR_BOOT_BACKDOOR              0xa0

#endif

#define  FLAG_FOR_BOOT_BACKDOOR              0xa0

#endif//MSH8_DRIVER__H
