//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef DWC_MSH8_REGMODEL_H
#define DWC_MSH8_REGMODEL_H

typedef union {
    struct {
        unsigned int BLOCKCNT_SDMASA : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_SDMASA_R_BLOCK_U;

typedef union {
    struct {
        unsigned int XFER_BLOCK_SIZE : 12; // [11:0]
        unsigned int SDMA_BUF_BDARY : 3; // [14:12]
        unsigned int RSVD_BLOCKSIZE15 : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_BLOCKSIZE_R_BLOCK_U;

typedef union {
    struct {
        unsigned int BLOCK_CNT : 16; // [15:0]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_BLOCKCOUNT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int ARGUMENT : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_ARGUMENT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int DMA_ENABLE : 1; // [0]
        unsigned int BLOCK_COUNT_ENABLE : 1; // [1]
        unsigned int AUTO_CMD_ENABLE : 2; // [3:2]
        unsigned int DATA_XFER_DIR : 1; // [4]
        unsigned int MULTI_BLK_SEL : 1; // [5]
        unsigned int RESP_TYPE : 1; // [6]
        unsigned int RESP_ERR_CHK_ENABLE : 1; // [7]
        unsigned int RESP_INT_DISABLE : 1; // [8]
        unsigned int RSVD : 7; // [15:9]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_XFER_MODE_R_BLOCK_U;

typedef union {
    struct {
        unsigned int RESP_TYPE_SELECT : 2; // [1:0]
        unsigned int SUB_CMD_FLAG : 1; // [2]
        unsigned int CMD_CRC_CHK_ENABLE : 1; // [3]
        unsigned int CMD_IDX_CHK_ENABLE : 1; // [4]
        unsigned int DATA_PRESENT_SEL : 1; // [5]
        unsigned int CMD_TYPE : 2; // [7:6]
        unsigned int CMD_INDEX : 6; // [13:8]
        unsigned int RSVD : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CMD_R_BLOCK_U;

typedef union {
    struct {
        unsigned int RESP01 : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_RESP01_R_BLOCK_U;

typedef union {
    struct {
        unsigned int RESP23 : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_RESP23_R_BLOCK_U;

typedef union {
    struct {
        unsigned int RESP45 : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_RESP45_R_BLOCK_U;

typedef union {
    struct {
        unsigned int RESP67 : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_RESP67_R_BLOCK_U;

typedef union {
    struct {
        unsigned int BUF_DATA : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_BUF_DATA_R_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_INHIBIT : 1; // [0]
        unsigned int CMD_INHIBIT_DAT : 1; // [1]
        unsigned int DAT_LINE_ACTIVE : 1; // [2]
        unsigned int RE_TUNE_REQ : 1; // [3]
        unsigned int DAT_7_4 : 4; // [7:4]
        unsigned int WR_XFER_ACTIVE : 1; // [8]
        unsigned int RD_XFER_ACTIVE : 1; // [9]
        unsigned int BUF_WR_ENABLE : 1; // [10]
        unsigned int BUF_RD_ENABLE : 1; // [11]
        unsigned int RSVD_15_12 : 4; // [15:12]
        unsigned int CARD_INSERTED : 1; // [16]
        unsigned int CARD_STABLE : 1; // [17]
        unsigned int CARD_DETECT_PIN_LEVEL : 1; // [18]
        unsigned int WR_PROTECT_SW_LVL : 1; // [19]
        unsigned int DAT_3_0 : 4; // [23:20]
        unsigned int CMD_LINE_LVL : 1; // [24]
        unsigned int HOST_REG_VOL : 1; // [25]
        unsigned int RSVD_26 : 1; // [26]
        unsigned int CMD_ISSUE_ERR : 1; // [27]
        unsigned int SUB_CMD_STAT : 1; // [28]
        unsigned int IN_DORMANT_ST : 1; // [29]
        unsigned int LANE_SYNC : 1; // [30]
        unsigned int UHS2_IF_DETECT : 1; // [31]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PSTATE_REG_BLOCK_U;

typedef union {
    struct {
        unsigned int LED_CTRL : 1; // [0]
        unsigned int DAT_XFER_WIDTH : 1; // [1]
        unsigned int HIGH_SPEED_EN : 1; // [2]
        unsigned int DMA_SEL : 2; // [4:3]
        unsigned int EXT_DAT_XFER : 1; // [5]
        unsigned int CARD_DETECT_TEST_LVL : 1; // [6]
        unsigned int CARD_DETECT_SIG_SEL : 1; // [7]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_HOST_CTRL1_R_BLOCK_U;

typedef union {
    struct {
        unsigned int SD_BUS_PWR_VDD1 : 1; // [0]
        unsigned int SD_BUS_VOL_VDD1 : 3; // [3:1]
        unsigned int SD_BUS_PWR_VDD2 : 1; // [4]
        unsigned int SD_BUS_VOL_VDD2 : 3; // [7:5]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PWR_CTRL_R_BLOCK_U;

typedef union {
    struct {
        unsigned int STOP_BG_REQ : 1; // [0]
        unsigned int CONTINUE_REQ : 1; // [1]
        unsigned int RD_WAIT_CTRL : 1; // [2]
        unsigned int INT_AT_BGAP : 1; // [3]
        unsigned int RSVD_7_4 : 4; // [7:4]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_BGAP_CTRL_R_BLOCK_U;

typedef union {
    struct {
        unsigned int CARD_INT : 1; // [0]
        unsigned int CARD_INSERT : 1; // [1]
        unsigned int CARD_REMOVAL : 1; // [2]
        unsigned int RSVD_7_3 : 5; // [7:3]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_WUP_CTRL_R_BLOCK_U;

typedef union {
    struct {
        unsigned int INTERNAL_CLK_EN : 1; // [0]
        unsigned int INTERNAL_CLK_STABLE : 1; // [1]
        unsigned int SD_CLK_EN : 1; // [2]
        unsigned int PLL_ENABLE : 1; // [3]
        unsigned int RSVD_4 : 1; // [4]
        unsigned int CLK_GEN_SELECT : 1; // [5]
        unsigned int UPPER_FREQ_SEL : 2; // [7:6]
        unsigned int FREQ_SEL : 8; // [15:8]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CLK_CTRL_R_BLOCK_U;

typedef union {
    struct {
        unsigned int TOUT_CNT : 4; // [3:0]
        unsigned int RSVD_7_4 : 4; // [7:4]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_TOUT_CTRL_R_BLOCK_U;

typedef union {
    struct {
        unsigned int SW_RST_ALL : 1; // [0]
        unsigned int SW_RST_CMD : 1; // [1]
        unsigned int SW_RST_DAT : 1; // [2]
        unsigned int RSVD_7_3 : 5; // [7:3]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_SW_RST_R_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_COMPLETE : 1; // [0]
        unsigned int XFER_COMPLETE : 1; // [1]
        unsigned int BGAP_EVENT : 1; // [2]
        unsigned int DMA_INTERRUPT : 1; // [3]
        unsigned int BUF_WR_READY : 1; // [4]
        unsigned int BUF_RD_READY : 1; // [5]
        unsigned int CARD_INSERTION : 1; // [6]
        unsigned int CARD_REMOVAL : 1; // [7]
        unsigned int CARD_INTERRUPT : 1; // [8]
        unsigned int INT_A : 1; // [9]
        unsigned int INT_B : 1; // [10]
        unsigned int INT_C : 1; // [11]
        unsigned int RE_TUNE_EVENT : 1; // [12]
        unsigned int FX_EVENT : 1; // [13]
        unsigned int CQE_EVENT : 1; // [14]
        unsigned int ERR_INTERRUPT : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_NORMAL_INT_STAT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_TOUT_ERR : 1; // [0]
        unsigned int CMD_CRC_ERR : 1; // [1]
        unsigned int CMD_END_BIT_ERR : 1; // [2]
        unsigned int CMD_IDX_ERR : 1; // [3]
        unsigned int DATA_TOUT_ERR : 1; // [4]
        unsigned int DATA_CRC_ERR : 1; // [5]
        unsigned int DATA_END_BIT_ERR : 1; // [6]
        unsigned int CUR_LMT_ERR : 1; // [7]
        unsigned int AUTO_CMD_ERR : 1; // [8]
        unsigned int ADMA_ERR : 1; // [9]
        unsigned int TUNING_ERR : 1; // [10]
        unsigned int RESP_ERR : 1; // [11]
        unsigned int BOOT_ACK_ERR : 1; // [12]
        unsigned int VENDOR_ERR1 : 1; // [13]
        unsigned int VENDOR_ERR2 : 1; // [14]
        unsigned int VENDOR_ERR3 : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_ERROR_INT_STAT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_COMPLETE_STAT_EN : 1; // [0]
        unsigned int XFER_COMPLETE_STAT_EN : 1; // [1]
        unsigned int BGAP_EVENT_STAT_EN : 1; // [2]
        unsigned int DMA_INTERRUPT_STAT_EN : 1; // [3]
        unsigned int BUF_WR_READY_STAT_EN : 1; // [4]
        unsigned int BUF_RD_READY_STAT_EN : 1; // [5]
        unsigned int CARD_INSERTION_STAT_EN : 1; // [6]
        unsigned int CARD_REMOVAL_STAT_EN : 1; // [7]
        unsigned int CARD_INTERRUPT_STAT_EN : 1; // [8]
        unsigned int INT_A_STAT_EN : 1; // [9]
        unsigned int INT_B_STAT_EN : 1; // [10]
        unsigned int INT_C_STAT_EN : 1; // [11]
        unsigned int RE_TUNE_EVENT_STAT_EN : 1; // [12]
        unsigned int FX_EVENT_STAT_EN : 1; // [13]
        unsigned int CQE_EVENT_STAT_EN : 1; // [14]
        unsigned int RSVD_15 : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_NORMAL_INT_STAT_EN_R_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_TOUT_ERR_STAT_EN : 1; // [0]
        unsigned int CMD_CRC_ERR_STAT_EN : 1; // [1]
        unsigned int CMD_END_BIT_ERR_STAT_EN : 1; // [2]
        unsigned int CMD_IDX_ERR_STAT_EN : 1; // [3]
        unsigned int DATA_TOUT_ERR_STAT_EN : 1; // [4]
        unsigned int DATA_CRC_ERR_STAT_EN : 1; // [5]
        unsigned int DATA_END_BIT_ERR_STAT_EN : 1; // [6]
        unsigned int CUR_LMT_ERR_STAT_EN : 1; // [7]
        unsigned int AUTO_CMD_ERR_STAT_EN : 1; // [8]
        unsigned int ADMA_ERR_STAT_EN : 1; // [9]
        unsigned int TUNING_ERR_STAT_EN : 1; // [10]
        unsigned int RESP_ERR_STAT_EN : 1; // [11]
        unsigned int BOOT_ACK_ERR_STAT_EN : 1; // [12]
        unsigned int VENDOR_ERR_STAT_EN1 : 1; // [13]
        unsigned int VENDOR_ERR_STAT_EN2 : 1; // [14]
        unsigned int VENDOR_ERR_STAT_EN3 : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_ERROR_INT_STAT_EN_R_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_COMPLETE_SIGNAL_EN : 1; // [0]
        unsigned int XFER_COMPLETE_SIGNAL_EN : 1; // [1]
        unsigned int BGAP_EVENT_SIGNAL_EN : 1; // [2]
        unsigned int DMA_INTERRUPT_SIGNAL_EN : 1; // [3]
        unsigned int BUF_WR_READY_SIGNAL_EN : 1; // [4]
        unsigned int BUF_RD_READY_SIGNAL_EN : 1; // [5]
        unsigned int CARD_INSERTION_SIGNAL_EN : 1; // [6]
        unsigned int CARD_REMOVAL_SIGNAL_EN : 1; // [7]
        unsigned int CARD_INTERRUPT_SIGNAL_EN : 1; // [8]
        unsigned int INT_A_SIGNAL_EN : 1; // [9]
        unsigned int INT_B_SIGNAL_EN : 1; // [10]
        unsigned int INT_C_SIGNAL_EN : 1; // [11]
        unsigned int RE_TUNE_EVENT_SIGNAL_EN : 1; // [12]
        unsigned int FX_EVENT_SIGNAL_EN : 1; // [13]
        unsigned int CQE_EVENT_SIGNAL_EN : 1; // [14]
        unsigned int RSVD_15 : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_NORMAL_INT_SIGNAL_EN_R_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_TOUT_ERR_SIGNAL_EN : 1; // [0]
        unsigned int CMD_CRC_ERR_SIGNAL_EN : 1; // [1]
        unsigned int CMD_END_BIT_ERR_SIGNAL_EN : 1; // [2]
        unsigned int CMD_IDX_ERR_SIGNAL_EN : 1; // [3]
        unsigned int DATA_TOUT_ERR_SIGNAL_EN : 1; // [4]
        unsigned int DATA_CRC_ERR_SIGNAL_EN : 1; // [5]
        unsigned int DATA_END_BIT_ERR_SIGNAL_EN : 1; // [6]
        unsigned int CUR_LMT_ERR_SIGNAL_EN : 1; // [7]
        unsigned int AUTO_CMD_ERR_SIGNAL_EN : 1; // [8]
        unsigned int ADMA_ERR_SIGNAL_EN : 1; // [9]
        unsigned int TUNING_ERR_SIGNAL_EN : 1; // [10]
        unsigned int RESP_ERR_SIGNAL_EN : 1; // [11]
        unsigned int BOOT_ACK_ERR_SIGNAL_EN : 1; // [12]
        unsigned int VENDOR_ERR_SIGNAL_EN1 : 1; // [13]
        unsigned int VENDOR_ERR_SIGNAL_EN2 : 1; // [14]
        unsigned int VENDOR_ERR_SIGNAL_EN3 : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_ERROR_INT_SIGNAL_EN_R_BLOCK_U;

typedef union {
    struct {
        unsigned int AUTO_CMD12_NOT_EXEC : 1; // [0]
        unsigned int AUTO_CMD_TOUT_ERR : 1; // [1]
        unsigned int AUTO_CMD_CRC_ERR : 1; // [2]
        unsigned int AUTO_CMD_EBIT_ERR : 1; // [3]
        unsigned int AUTO_CMD_IDX_ERR : 1; // [4]
        unsigned int AUTO_CMD_RESP_ERR : 1; // [5]
        unsigned int RSVD_6 : 1; // [6]
        unsigned int CMD_NOT_ISSUED_AUTO_CMD12 : 1; // [7]
        unsigned int RSVD_15_8 : 8; // [15:8]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_AUTO_CMD_STAT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int UHS_MODE_SEL : 3; // [2:0]
        unsigned int SIGNALING_EN : 1; // [3]
        unsigned int DRV_STRENGTH_SEL : 2; // [5:4]
        unsigned int EXEC_TUNING : 1; // [6]
        unsigned int SAMPLE_CLK_SEL : 1; // [7]
        unsigned int UHS2_IF_ENABLE : 1; // [8]
        unsigned int RSVD_9 : 1; // [9]
        unsigned int ADMA2_LEN_MODE : 1; // [10]
        unsigned int CMD23_ENABLE : 1; // [11]
        unsigned int HOST_VER4_ENABLE : 1; // [12]
        unsigned int ADDRESSING : 1; // [13]
        unsigned int ASYNC_INT_ENABLE : 1; // [14]
        unsigned int PRESET_VAL_ENABLE : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_HOST_CTRL2_R_BLOCK_U;

typedef union {
    struct {
        unsigned int TOUT_CLK_FREQ : 6; // [5:0]
        unsigned int RSVD_6 : 1; // [6]
        unsigned int TOUT_CLK_UNIT : 1; // [7]
        unsigned int BASE_CLK_FREQ : 8; // [15:8]
        unsigned int MAX_BLK_LEN : 2; // [17:16]
        unsigned int Embedded_8_BIT : 1; // [18]
        unsigned int ADMA2_SUPPORT : 1; // [19]
        unsigned int RSVD_20 : 1; // [20]
        unsigned int HIGH_SPEED_SUPPORT : 1; // [21]
        unsigned int SDMA_SUPPORT : 1; // [22]
        unsigned int SUS_RES_SUPPORT : 1; // [23]
        unsigned int VOLT_33 : 1; // [24]
        unsigned int VOLT_30 : 1; // [25]
        unsigned int VOLT_18 : 1; // [26]
        unsigned int SYS_ADDR_64_V4 : 1; // [27]
        unsigned int SYS_ADDR_64_V3 : 1; // [28]
        unsigned int ASYNC_INT_SUPPORT : 1; // [29]
        unsigned int SLOT_TYPE_R : 2; // [31:30]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CAPABILITIES1_R_BLOCK_U;

typedef union {
    struct {
        unsigned int SDR50_SUPPORT : 1; // [0]
        unsigned int SDR104_SUPPORT : 1; // [1]
        unsigned int DDR50_SUPPORT : 1; // [2]
        unsigned int UHS2_SUPPORT : 1; // [3]
        unsigned int DRV_TYPEA : 1; // [4]
        unsigned int DRV_TYPEC : 1; // [5]
        unsigned int DRV_TYPED : 1; // [6]
        unsigned int RSVD_39 : 1; // [7]
        unsigned int RETUNE_CNT : 4; // [11:8]
        unsigned int RSVD_44 : 1; // [12]
        unsigned int USE_TUNING_SDR50 : 1; // [13]
        unsigned int RE_TUNING_MODES : 2; // [15:14]
        unsigned int CLK_MUL : 8; // [23:16]
        unsigned int RSVD_56_58 : 3; // [26:24]
        unsigned int ADMA3_SUPPORT : 1; // [27]
        unsigned int VDD2_18V_SUPPORT : 1; // [28]
        unsigned int RSVD_61 : 1; // [29]
        unsigned int RSVD_62_63 : 2; // [31:30]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CAPABILITIES2_R_BLOCK_U;

typedef union {
    struct {
        unsigned int MAX_CUR_33V : 8; // [7:0]
        unsigned int MAX_CUR_30V : 8; // [15:8]
        unsigned int MAX_CUR_18V : 8; // [23:16]
        unsigned int RSVD_31_24 : 8; // [31:24]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CURR_CAPABILITIES1_R_BLOCK_U;

typedef union {
    struct {
        unsigned int MAX_CUR_VDD2_18V : 8; // [7:0]
        unsigned int RSVD_63_40 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CURR_CAPABILITIES2_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FORCE_AUTO_CMD12_NOT_EXEC : 1; // [0]
        unsigned int FORCE_AUTO_CMD_TOUT_ERR : 1; // [1]
        unsigned int FORCE_AUTO_CMD_CRC_ERR : 1; // [2]
        unsigned int FORCE_AUTO_CMD_EBIT_ERR : 1; // [3]
        unsigned int FORCE_AUTO_CMD_IDX_ERR : 1; // [4]
        unsigned int FORCE_AUTO_CMD_RESP_ERR : 1; // [5]
        unsigned int RSVD_6 : 1; // [6]
        unsigned int FORCE_CMD_NOT_ISSUED_AUTO_CMD12 : 1; // [7]
        unsigned int RSVD_15_8 : 8; // [15:8]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_FORCE_AUTO_CMD_STAT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FORCE_CMD_TOUT_ERR : 1; // [0]
        unsigned int FORCE_CMD_CRC_ERR : 1; // [1]
        unsigned int FORCE_CMD_END_BIT_ERR : 1; // [2]
        unsigned int FORCE_CMD_IDX_ERR : 1; // [3]
        unsigned int FORCE_DATA_TOUT_ERR : 1; // [4]
        unsigned int FORCE_DATA_CRC_ERR : 1; // [5]
        unsigned int FORCE_DATA_END_BIT_ERR : 1; // [6]
        unsigned int FORCE_CUR_LMT_ERR : 1; // [7]
        unsigned int FORCE_AUTO_CMD_ERR : 1; // [8]
        unsigned int FORCE_ADMA_ERR : 1; // [9]
        unsigned int FORCE_TUNING_ERR : 1; // [10]
        unsigned int FORCE_RESP_ERR : 1; // [11]
        unsigned int FORCE_BOOT_ACK_ERR : 1; // [12]
        unsigned int FORCE_VENDOR_ERR1 : 1; // [13]
        unsigned int FORCE_VENDOR_ERR2 : 1; // [14]
        unsigned int FORCE_VENDOR_ERR3 : 1; // [15]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_FORCE_ERROR_INT_STAT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int ADMA_ERR_STATES : 2; // [1:0]
        unsigned int ADMA_LEN_ERR : 1; // [2]
        unsigned int RSVD_7_3 : 5; // [7:3]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_ADMA_ERR_STAT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int ADMA_SA_LOW : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_ADMA_SA_LOW_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_INIT_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_DS_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_HS_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_SDR12_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_SDR25_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_SDR50_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_SDR104_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_DDR50_R_BLOCK_U;

typedef union {
    struct {
        unsigned int FREQ_SEL_VAL : 10; // [9:0]
        unsigned int CLK_GEN_SEL_VAL : 1; // [10]
        unsigned int RSVD_13_11 : 3; // [13:11]
        unsigned int DRV_SEL_VAL : 2; // [15:14]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRESET_UHS2_R_BLOCK_U;

typedef union {
    struct {
        unsigned int ADMA_ID_LOW : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_ADMA_ID_LOW_R_BLOCK_U;

typedef union {
    struct {
        unsigned int REG_OFFSET_ADDR : 12; // [11:0]
        unsigned int RESERVED_15_12 : 4; // [15:12]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_P_EMBEDDED_CNTRL_BLOCK_U;

typedef union {
    struct {
        unsigned int REG_OFFSET_ADDR : 12; // [11:0]
        unsigned int RESERVED_15_12 : 4; // [15:12]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_P_VENDOR_SPECIFIC_AREA_BLOCK_U;

typedef union {
    struct {
        unsigned int REG_OFFSET_ADDR : 16; // [15:0]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_P_VENDOR2_SPECIFIC_AREA_BLOCK_U;

typedef union {
    struct {
        unsigned int INTR_SLOT : 8; // [7:0]
        unsigned int RESERVED_15_8 : 8; // [15:8]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_SLOT_INTR_STATUS_R_BLOCK_U;

typedef union {
    struct {
        unsigned int SPEC_VERSION_NUM : 8; // [7:0]
        unsigned int VENDOR_VERSION_NUM : 8; // [15:8]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_HOST_CNTRL_VERS_R_BLOCK_U;

typedef union {
    struct {
        unsigned int NUM_CLK_PIN : 3; // [2:0]
        unsigned int RSVD_3 : 1; // [3]
        unsigned int NUM_INT_PIN : 2; // [5:4]
        unsigned int RSVD_7_6 : 2; // [7:6]
        unsigned int BUS_WIDTH_PRESET : 7; // [14:8]
        unsigned int RSVD_15 : 1; // [15]
        unsigned int CLK_PIN_SEL : 3; // [18:16]
        unsigned int RSVD_19 : 1; // [19]
        unsigned int INT_PIN_SEL : 3; // [22:20]
        unsigned int RSVD_23 : 1; // [23]
        unsigned int BACK_END_PWR_CTRL : 7; // [30:24]
        unsigned int RSVD_31 : 1; // [31]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_EMBEDDED_CTRL_R_EMBEDDED_CONTROL_BLOCK_U;

typedef union {
    struct {
        unsigned int MSHC_VER_ID : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_MSHC_VER_ID_R_VENDOR1_BLOCK_U;

typedef union {
    struct {
        unsigned int MSHC_VER_TYPE : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_MSHC_VER_TYPE_R_VENDOR1_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_CONFLICT_CHECK : 1; // [0]
        unsigned int RSVD1 : 3; // [3:1]
        unsigned int SW_CG_DIS : 1; // [4]
        unsigned int Reserved_5_7 : 3; // [7:5]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_MSHC_CTRL_R_VENDOR1_BLOCK_U;

typedef union {
    struct {
        unsigned int UNDEFL_INCR_EN : 1; // [0]
        unsigned int BURST_INCR4_EN : 1; // [1]
        unsigned int BURST_INCR8_EN : 1; // [2]
        unsigned int BURST_INCR16_EN : 1; // [3]
        unsigned int RSVD : 4; // [7:4]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_MBIU_CTRL_R_VENDOR1_BLOCK_U;

typedef union {
    struct {
        unsigned int CARD_IS_EMMC : 1; // [0]
        unsigned int DISABLE_DATA_CRC_CHK : 1; // [1]
        unsigned int EMMC_RST_N : 1; // [2]
        unsigned int EMMC_RST_N_OE : 1; // [3]
        unsigned int Reserved_4_7 : 4; // [7:4]
        unsigned int ENH_STROBE_ENABLE : 1; // [8]
        unsigned int CQE_ALGO_SEL : 1; // [9]
        unsigned int CQE_PREFETCH_DISABLE : 1; // [10]
        unsigned int RSVD : 5; // [15:11]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_EMMC_CTRL_R_VENDOR1_BLOCK_U;

typedef union {
    struct {
        unsigned int MAN_BOOT_EN : 1; // [0]
        unsigned int RSVD_6_1 : 6; // [6:1]
        unsigned int VALIDATE_BOOT : 1; // [7]
        unsigned int BOOT_ACK_ENABLE : 1; // [8]
        unsigned int RSVD_11_9 : 3; // [11:9]
        unsigned int BOOT_TOUT_CNT : 4; // [15:12]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_BOOT_CTRL_R_VENDOR1_BLOCK_U;

typedef union {
    struct {
        unsigned int AT_EN : 1; // [0]
        unsigned int CI_SEL : 1; // [1]
        unsigned int SWIN_TH_EN : 1; // [2]
        unsigned int RPT_TUNE_ERR : 1; // [3]
        unsigned int SW_TUNE_EN : 1; // [4]
        unsigned int RSDV2 : 3; // [7:5]
        unsigned int WIN_EDGE_SEL : 4; // [11:8]
        unsigned int RSDV3 : 4; // [15:12]
        unsigned int TUNE_CLK_STOP_EN : 1; // [16]
        unsigned int PRE_CHANGE_DLY : 2; // [18:17]
        unsigned int POST_CHANGE_DLY : 2; // [20:19]
        unsigned int Reserved_21_23 : 3; // [23:21]
        unsigned int SWIN_TH_VAL : 7; // [30:24]
        unsigned int Reserved_31_31 : 1; // [31]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_AT_CTRL_R_VENDOR1_BLOCK_U;

typedef union {
    struct {
        unsigned int CENTER_PH_CODE : 8; // [7:0]
        unsigned int R_EDGE_PH_CODE : 8; // [15:8]
        unsigned int L_EDGE_PH_CODE : 8; // [23:16]
        unsigned int RSDV1 : 8; // [31:24]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_AT_STAT_R_VENDOR1_BLOCK_U;

typedef union {
    struct {
        unsigned int EMMC_VER_SUFFIX : 4; // [3:0]
        unsigned int EMMC_VER_MINOR : 4; // [7:4]
        unsigned int EMMC_VER_MAJOR : 4; // [11:8]
        unsigned int EMMMC_VER_RSVD : 20; // [31:12]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQVER_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int ITCFVAL : 10; // [9:0]
        unsigned int CQCCAP_RSVD1 : 2; // [11:10]
        unsigned int ITCFMUL : 4; // [15:12]
        unsigned int CQCCAP_RSVD2 : 12; // [27:16]
        unsigned int CRYPTO_SUPPORT : 1; // [28]
        unsigned int CQCCAP_RSVD3 : 3; // [31:29]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQCAP_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int CQ_EN : 1; // [0]
        unsigned int Reserved_1_1 : 1; // [1]
        unsigned int CQCCFG_RSVD1 : 6; // [7:2]
        unsigned int TASK_DESC_SIZE : 1; // [8]
        unsigned int CQCCFG_RSVD2 : 3; // [11:9]
        unsigned int DCMD_EN : 1; // [12]
        unsigned int CQCCFG_RSVD3 : 19; // [31:13]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQCFG_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int HALT : 1; // [0]
        unsigned int CQCTL_RSVD1 : 7; // [7:1]
        unsigned int CLR_ALL_TASKS : 1; // [8]
        unsigned int CQCTL_RSVD2 : 23; // [31:9]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQCTL_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int HAC : 1; // [0]
        unsigned int TCC : 1; // [1]
        unsigned int RED : 1; // [2]
        unsigned int TCL : 1; // [3]
        unsigned int Reserved_4_5 : 2; // [5:4]
        unsigned int CQIS_RSVD1 : 26; // [31:6]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQIS_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int HAC_STE : 1; // [0]
        unsigned int TCC_STE : 1; // [1]
        unsigned int RED_STE : 1; // [2]
        unsigned int TCL_STE : 1; // [3]
        unsigned int Reserved_4_5 : 2; // [5:4]
        unsigned int CQISTE_RSVD1 : 26; // [31:6]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQISE_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int HAC_SGE : 1; // [0]
        unsigned int TCC_SGE : 1; // [1]
        unsigned int RED_SGE : 1; // [2]
        unsigned int TCL_SGE : 1; // [3]
        unsigned int Reserved_4_5 : 2; // [5:4]
        unsigned int CQISGE_RSVD1 : 26; // [31:6]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQISGE_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int TOUT_VAL : 7; // [6:0]
        unsigned int TOUT_VAL_WEN : 1; // [7]
        unsigned int INTC_TH : 5; // [12:8]
        unsigned int CQIC_RSVD1 : 2; // [14:13]
        unsigned int INTC_TH_WEN : 1; // [15]
        unsigned int INTC_RST : 1; // [16]
        unsigned int CQIC_RSVD2 : 3; // [19:17]
        unsigned int INTC_STAT : 1; // [20]
        unsigned int CQIC_RSVD3 : 10; // [30:21]
        unsigned int INTC_EN : 1; // [31]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQIC_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int TDLBA : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQTDLBA_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int DBR : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQTDBR_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int TCN : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQTCN_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int DQS : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQDQS_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int DPT : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQDPT_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int TCLR : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQTCLR_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int SQSCMD_IDLE_TMR : 16; // [15:0]
        unsigned int SQSCMD_BLK_CNT : 4; // [19:16]
        unsigned int RSVD_20_31 : 12; // [31:20]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQSSC1_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int SQSCMD_RCA : 16; // [15:0]
        unsigned int RSVD_16_31 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQSSC2_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int DCMD_RESP : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQCRDCT_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int RESP_ERR_MASK : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQRMEM_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int RESP_ERR_CMD_INDX : 6; // [5:0]
        unsigned int RSVD_6_7 : 2; // [7:6]
        unsigned int RESP_ERR_TASKID : 5; // [12:8]
        unsigned int RSVD_13_14 : 2; // [14:13]
        unsigned int RESP_ERR_FIELDS_VALID : 1; // [15]
        unsigned int TRANS_ERR_CMD_INDX : 6; // [21:16]
        unsigned int RSVD_23_22 : 2; // [23:22]
        unsigned int TRANS_ERR_TASKID : 5; // [28:24]
        unsigned int RSVD_30_29 : 2; // [30:29]
        unsigned int TRANS_ERR_FIELDS_VALID : 1; // [31]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQTERRI_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_RESP_INDX : 6; // [5:0]
        unsigned int RSVD_31_6 : 26; // [31:6]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQCRI_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int CMD_RESP_ARG : 32; // [31:0]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CQCRA_VENDOR2_BLOCK_U;

typedef union {
    struct {
        unsigned int PHY_RSTN : 1; // [0]
        unsigned int PHY_PWRGOOD : 1; // [1]
        unsigned int Reserved_2_15 : 14; // [15:2]
        unsigned int PAD_SP : 4; // [19:16]
        unsigned int PAD_SN : 4; // [23:20]
        unsigned int Reserved_24_31 : 8; // [31:24]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PHY_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int RXSEL : 3; // [2:0]
        unsigned int WEAKPULL_EN : 2; // [4:3]
        unsigned int TXSLEW_CTRL_P : 4; // [8:5]
        unsigned int TXSLEW_CTRL_N : 4; // [12:9]
        unsigned int Reserved_13_15 : 3; // [15:13]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CMDPAD_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int RXSEL : 3; // [2:0]
        unsigned int WEAKPULL_EN : 2; // [4:3]
        unsigned int TXSLEW_CTRL_P : 4; // [8:5]
        unsigned int TXSLEW_CTRL_N : 4; // [12:9]
        unsigned int Reserved_13_15 : 3; // [15:13]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DATPAD_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int RXSEL : 3; // [2:0]
        unsigned int WEAKPULL_EN : 2; // [4:3]
        unsigned int TXSLEW_CTRL_P : 4; // [8:5]
        unsigned int TXSLEW_CTRL_N : 4; // [12:9]
        unsigned int Reserved_13_15 : 3; // [15:13]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_CLKPAD_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int RXSEL : 3; // [2:0]
        unsigned int WEAKPULL_EN : 2; // [4:3]
        unsigned int TXSLEW_CTRL_P : 4; // [8:5]
        unsigned int TXSLEW_CTRL_N : 4; // [12:9]
        unsigned int Reserved_13_15 : 3; // [15:13]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_STBPAD_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int RXSEL : 3; // [2:0]
        unsigned int WEAKPULL_EN : 2; // [4:3]
        unsigned int TXSLEW_CTRL_P : 4; // [8:5]
        unsigned int TXSLEW_CTRL_N : 4; // [12:9]
        unsigned int Reserved_13_15 : 3; // [15:13]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_RSTNPAD_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int TESTMODE_EN : 1; // [0]
        unsigned int RSVD_1 : 3; // [3:1]
        unsigned int TEST_OE : 12; // [15:4]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PADTEST_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int TESTDATA_OUT : 12; // [11:0]
        unsigned int Reserved_12_15 : 4; // [15:12]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PADTEST_OUT_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int TESTDATA_IN : 12; // [11:0]
        unsigned int Reserved_12_15 : 4; // [15:12]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PADTEST_IN_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int INIT_SEED : 16; // [15:0]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PRBS_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int PHYLPBK_EN : 1; // [0]
        unsigned int OUT_EN_PHYLPBK_MODE : 1; // [1]
        unsigned int Reserved_2_7 : 6; // [7:2]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_PHYLPBK_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int DLSTEP_SEL : 1; // [0]
        unsigned int DLOUT_EN : 1; // [1]
        unsigned int Reserved_2_7 : 6; // [7:2]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_COMMDL_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int EXTDLY_EN : 1; // [0]
        unsigned int BYPASS_EN : 1; // [1]
        unsigned int INPSEL_CNFG : 2; // [3:2]
        unsigned int UPDATE_DC : 1; // [4]
        unsigned int Reserved_5_7 : 3; // [7:5]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_SDCLKDL_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int CCKDL_DC : 7; // [6:0]
        unsigned int Reserved_7_7 : 1; // [7]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_SDCLKDL_DC_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int EXTDLY_EN : 1; // [0]
        unsigned int BYPASS_EN : 1; // [1]
        unsigned int INPSEL_CNFG : 2; // [3:2]
        unsigned int INPSEL_OVERRIDE : 1; // [4]
        unsigned int Reserved_5_7 : 3; // [7:5]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_SMPLDL_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int EXTDLY_EN : 1; // [0]
        unsigned int BYPASS_EN : 1; // [1]
        unsigned int INPSEL_CNFG : 2; // [3:2]
        unsigned int Reserved_4_7 : 4; // [7:4]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_ATDL_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int DLL_EN : 1; // [0]
        unsigned int OFFST_EN : 1; // [1]
        unsigned int SLV_SWDC_UPDATE : 1; // [2]
        unsigned int RSVD_3_7 : 5; // [7:3]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLL_CTRL_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int WAITCYCLE : 3; // [2:0]
        unsigned int Reserved_3_3 : 1; // [3]
        unsigned int SLVDLY : 2; // [5:4]
        unsigned int Reserved_6_7 : 2; // [7:6]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLL_CNFG1_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int JUMPSTEP : 7; // [6:0]
        unsigned int Reserved_7_7 : 1; // [7]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLL_CNFG2_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int MST_EXTDLYEN : 1; // [0]
        unsigned int MST_INPSEL : 2; // [2:1]
        unsigned int MST_BYPASS : 1; // [3]
        unsigned int SLV_EXTDLYEN : 1; // [4]
        unsigned int SLV_INPSEL : 2; // [6:5]
        unsigned int SLV_BYPASS : 1; // [7]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLLDL_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int OFFST : 7; // [6:0]
        unsigned int Reserved_7_7 : 1; // [7]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLL_OFFST_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int MSTTST_DC : 7; // [6:0]
        unsigned int Reserved_7_7 : 1; // [7]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLLMST_TSTDC_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int LBT_LOADVAL : 16; // [15:0]
        unsigned int RESERVED_0 : 16; // [31:16]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLLLBT_CNFG_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int LOCK_STS : 1; // [0]
        unsigned int ERROR_STS : 1; // [1]
        unsigned int Reserved_2_7 : 6; // [7:2]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLL_STATUS_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int MSTLKDC : 7; // [6:0]
        unsigned int Reserved_7_7 : 1; // [7]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLLDBG_MLKDC_PHY_BLOCK_U;

typedef union {
    struct {
        unsigned int SLVLKDC : 7; // [6:0]
        unsigned int Reserved_7_7 : 1; // [7]
        unsigned int RESERVED_0 : 24; // [31:8]
    };
    unsigned int u32;
} DWC_MSH8_REGMODEL_DLLDBG_SLKDC_PHY_BLOCK_U;

typedef union {
    volatile DWC_MSH8_REGMODEL_SDMASA_R_BLOCK_U dwc_msh8_regmodel_sdmasa_r;    // 0x0
    volatile DWC_MSH8_REGMODEL_BLOCKSIZE_R_BLOCK_U dwc_msh8_regmodel_blocksize_r;    // 0x4
    volatile DWC_MSH8_REGMODEL_BLOCKCOUNT_R_BLOCK_U dwc_msh8_regmodel_blockcount_r;    // 0x6
    volatile DWC_MSH8_REGMODEL_ARGUMENT_R_BLOCK_U dwc_msh8_regmodel_argument_r;    // 0x8
    volatile DWC_MSH8_REGMODEL_XFER_MODE_R_BLOCK_U dwc_msh8_regmodel_xfer_mode_r;    // 0xc
    volatile DWC_MSH8_REGMODEL_CMD_R_BLOCK_U dwc_msh8_regmodel_cmd_r;    // 0xe
    volatile DWC_MSH8_REGMODEL_RESP01_R_BLOCK_U dwc_msh8_regmodel_resp01_r;    // 0x10
    volatile DWC_MSH8_REGMODEL_RESP23_R_BLOCK_U dwc_msh8_regmodel_resp23_r;    // 0x14
    volatile DWC_MSH8_REGMODEL_RESP45_R_BLOCK_U dwc_msh8_regmodel_resp45_r;    // 0x18
    volatile DWC_MSH8_REGMODEL_RESP67_R_BLOCK_U dwc_msh8_regmodel_resp67_r;    // 0x1c
    volatile DWC_MSH8_REGMODEL_BUF_DATA_R_BLOCK_U dwc_msh8_regmodel_buf_data_r;    // 0x20
    volatile DWC_MSH8_REGMODEL_PSTATE_REG_BLOCK_U dwc_msh8_regmodel_pstate_reg_msh8_dwc_mshc_map_dwc_mshc;    // 0x24
    volatile DWC_MSH8_REGMODEL_HOST_CTRL1_R_BLOCK_U dwc_msh8_regmodel_host_ctrl1_r;    // 0x28
    volatile DWC_MSH8_REGMODEL_PWR_CTRL_R_BLOCK_U dwc_msh8_regmodel_pwr_ctrl_r;    // 0x29
    volatile DWC_MSH8_REGMODEL_BGAP_CTRL_R_BLOCK_U dwc_msh8_regmodel_bgap_ctrl_r;    // 0x2a
    volatile DWC_MSH8_REGMODEL_WUP_CTRL_R_BLOCK_U dwc_msh8_regmodel_wup_ctrl_r;    // 0x2b
    volatile DWC_MSH8_REGMODEL_CLK_CTRL_R_BLOCK_U dwc_msh8_regmodel_clk_ctrl_r;    // 0x2c
    volatile DWC_MSH8_REGMODEL_TOUT_CTRL_R_BLOCK_U dwc_msh8_regmodel_tout_ctrl_r;    // 0x2e
    volatile DWC_MSH8_REGMODEL_SW_RST_R_BLOCK_U dwc_msh8_regmodel_sw_rst_r;    // 0x2f
    volatile DWC_MSH8_REGMODEL_NORMAL_INT_STAT_R_BLOCK_U dwc_msh8_regmodel_normal_int_stat_r;    // 0x30
    volatile DWC_MSH8_REGMODEL_ERROR_INT_STAT_R_BLOCK_U dwc_msh8_regmodel_error_int_stat_r;    // 0x32
    volatile DWC_MSH8_REGMODEL_NORMAL_INT_STAT_EN_R_BLOCK_U dwc_msh8_regmodel_normal_int_stat_en_r;    // 0x34
    volatile DWC_MSH8_REGMODEL_ERROR_INT_STAT_EN_R_BLOCK_U dwc_msh8_regmodel_error_int_stat_en_r;    // 0x36
    volatile DWC_MSH8_REGMODEL_NORMAL_INT_SIGNAL_EN_R_BLOCK_U dwc_msh8_regmodel_normal_int_signal_en_r;    // 0x38
    volatile DWC_MSH8_REGMODEL_ERROR_INT_SIGNAL_EN_R_BLOCK_U dwc_msh8_regmodel_error_int_signal_en_r;    // 0x3a
    volatile DWC_MSH8_REGMODEL_AUTO_CMD_STAT_R_BLOCK_U dwc_msh8_regmodel_auto_cmd_stat_r;    // 0x3c
    volatile DWC_MSH8_REGMODEL_HOST_CTRL2_R_BLOCK_U dwc_msh8_regmodel_host_ctrl2_r;    // 0x3e
    volatile DWC_MSH8_REGMODEL_CAPABILITIES1_R_BLOCK_U dwc_msh8_regmodel_capabilities1_r;    // 0x40
    volatile DWC_MSH8_REGMODEL_CAPABILITIES2_R_BLOCK_U dwc_msh8_regmodel_capabilities2_r;    // 0x44
    volatile DWC_MSH8_REGMODEL_CURR_CAPABILITIES1_R_BLOCK_U dwc_msh8_regmodel_curr_capabilities1_r;    // 0x48
    volatile DWC_MSH8_REGMODEL_CURR_CAPABILITIES2_R_BLOCK_U dwc_msh8_regmodel_curr_capabilities2_r;    // 0x4c
    volatile DWC_MSH8_REGMODEL_FORCE_AUTO_CMD_STAT_R_BLOCK_U dwc_msh8_regmodel_force_auto_cmd_stat_r;    // 0x50
    volatile DWC_MSH8_REGMODEL_FORCE_ERROR_INT_STAT_R_BLOCK_U dwc_msh8_regmodel_force_error_int_stat_r;    // 0x52
    volatile DWC_MSH8_REGMODEL_ADMA_ERR_STAT_R_BLOCK_U dwc_msh8_regmodel_adma_err_stat_r;    // 0x54
    volatile DWC_MSH8_REGMODEL_ADMA_SA_LOW_R_BLOCK_U dwc_msh8_regmodel_adma_sa_low_r;    // 0x58
    volatile DWC_MSH8_REGMODEL_PRESET_INIT_R_BLOCK_U dwc_msh8_regmodel_preset_init_r;    // 0x60
    volatile DWC_MSH8_REGMODEL_PRESET_DS_R_BLOCK_U dwc_msh8_regmodel_preset_ds_r;    // 0x62
    volatile DWC_MSH8_REGMODEL_PRESET_HS_R_BLOCK_U dwc_msh8_regmodel_preset_hs_r;    // 0x64
    volatile DWC_MSH8_REGMODEL_PRESET_SDR12_R_BLOCK_U dwc_msh8_regmodel_preset_sdr12_r;    // 0x66
    volatile DWC_MSH8_REGMODEL_PRESET_SDR25_R_BLOCK_U dwc_msh8_regmodel_preset_sdr25_r;    // 0x68
    volatile DWC_MSH8_REGMODEL_PRESET_SDR50_R_BLOCK_U dwc_msh8_regmodel_preset_sdr50_r;    // 0x6a
    volatile DWC_MSH8_REGMODEL_PRESET_SDR104_R_BLOCK_U dwc_msh8_regmodel_preset_sdr104_r;    // 0x6c
    volatile DWC_MSH8_REGMODEL_PRESET_DDR50_R_BLOCK_U dwc_msh8_regmodel_preset_ddr50_r;    // 0x6e
    volatile DWC_MSH8_REGMODEL_PRESET_UHS2_R_BLOCK_U dwc_msh8_regmodel_preset_uhs2_r;    // 0x74
    volatile DWC_MSH8_REGMODEL_ADMA_ID_LOW_R_BLOCK_U dwc_msh8_regmodel_adma_id_low_r;    // 0x78
    volatile DWC_MSH8_REGMODEL_P_EMBEDDED_CNTRL_BLOCK_U dwc_msh8_regmodel_p_embedded_cntrl_msh8_dwc_mshc_map_dwc_mshc;    // 0xe6
    volatile DWC_MSH8_REGMODEL_P_VENDOR_SPECIFIC_AREA_BLOCK_U dwc_msh8_regmodel_p_vendor_specific_area_msh8_dwc_mshc_map_dwc_mshc;    // 0xe8
    volatile DWC_MSH8_REGMODEL_P_VENDOR2_SPECIFIC_AREA_BLOCK_U dwc_msh8_regmodel_p_vendor2_specific_area_msh8_dwc_mshc_map_dwc_mshc;    // 0xea
    volatile DWC_MSH8_REGMODEL_SLOT_INTR_STATUS_R_BLOCK_U dwc_msh8_regmodel_slot_intr_status_r;    // 0xfc
    volatile DWC_MSH8_REGMODEL_HOST_CNTRL_VERS_R_BLOCK_U dwc_msh8_regmodel_host_cntrl_vers_r;    // 0xfe
    volatile DWC_MSH8_REGMODEL_EMBEDDED_CTRL_R_EMBEDDED_CONTROL_BLOCK_U dwc_msh8_regmodel_embedded_ctrl_r_embedded_control;    // 0xf6c
    volatile DWC_MSH8_REGMODEL_MSHC_VER_ID_R_VENDOR1_BLOCK_U dwc_msh8_regmodel_mshc_ver_id_r_vendor1;    // 0x500
    volatile DWC_MSH8_REGMODEL_MSHC_VER_TYPE_R_VENDOR1_BLOCK_U dwc_msh8_regmodel_mshc_ver_type_r_vendor1;    // 0x504
    volatile DWC_MSH8_REGMODEL_MSHC_CTRL_R_VENDOR1_BLOCK_U dwc_msh8_regmodel_mshc_ctrl_r_vendor1;    // 0x508
    volatile DWC_MSH8_REGMODEL_MBIU_CTRL_R_VENDOR1_BLOCK_U dwc_msh8_regmodel_mbiu_ctrl_r_vendor1;    // 0x510
    volatile DWC_MSH8_REGMODEL_EMMC_CTRL_R_VENDOR1_BLOCK_U dwc_msh8_regmodel_emmc_ctrl_r_vendor1;    // 0x52c
    volatile DWC_MSH8_REGMODEL_BOOT_CTRL_R_VENDOR1_BLOCK_U dwc_msh8_regmodel_boot_ctrl_r_vendor1;    // 0x52e
    volatile DWC_MSH8_REGMODEL_AT_CTRL_R_VENDOR1_BLOCK_U dwc_msh8_regmodel_at_ctrl_r_vendor1;    // 0x540
    volatile DWC_MSH8_REGMODEL_AT_STAT_R_VENDOR1_BLOCK_U dwc_msh8_regmodel_at_stat_r_vendor1;    // 0x544
    volatile DWC_MSH8_REGMODEL_CQVER_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqver_vendor2;    // 0x180
    volatile DWC_MSH8_REGMODEL_CQCAP_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqcap_vendor2;    // 0x184
    volatile DWC_MSH8_REGMODEL_CQCFG_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqcfg_vendor2;    // 0x188
    volatile DWC_MSH8_REGMODEL_CQCTL_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqctl_vendor2;    // 0x18c
    volatile DWC_MSH8_REGMODEL_CQIS_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqis_vendor2;    // 0x190
    volatile DWC_MSH8_REGMODEL_CQISE_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqise_vendor2;    // 0x194
    volatile DWC_MSH8_REGMODEL_CQISGE_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqisge_vendor2;    // 0x198
    volatile DWC_MSH8_REGMODEL_CQIC_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqic_vendor2;    // 0x19c
    volatile DWC_MSH8_REGMODEL_CQTDLBA_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqtdlba_vendor2;    // 0x1a0
    volatile DWC_MSH8_REGMODEL_CQTDBR_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqtdbr_vendor2;    // 0x1a8
    volatile DWC_MSH8_REGMODEL_CQTCN_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqtcn_vendor2;    // 0x1ac
    volatile DWC_MSH8_REGMODEL_CQDQS_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqdqs_vendor2;    // 0x1b0
    volatile DWC_MSH8_REGMODEL_CQDPT_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqdpt_vendor2;    // 0x1b4
    volatile DWC_MSH8_REGMODEL_CQTCLR_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqtclr_vendor2;    // 0x1b8
    volatile DWC_MSH8_REGMODEL_CQSSC1_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqssc1_vendor2;    // 0x1c0
    volatile DWC_MSH8_REGMODEL_CQSSC2_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqssc2_vendor2;    // 0x1c4
    volatile DWC_MSH8_REGMODEL_CQCRDCT_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqcrdct_vendor2;    // 0x1c8
    volatile DWC_MSH8_REGMODEL_CQRMEM_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqrmem_vendor2;    // 0x1d0
    volatile DWC_MSH8_REGMODEL_CQTERRI_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqterri_vendor2;    // 0x1d4
    volatile DWC_MSH8_REGMODEL_CQCRI_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqcri_vendor2;    // 0x1d8
    volatile DWC_MSH8_REGMODEL_CQCRA_VENDOR2_BLOCK_U dwc_msh8_regmodel_cqcra_vendor2;    // 0x1dc
    volatile DWC_MSH8_REGMODEL_PHY_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_phy_cnfg_phy;    // 0x300
    volatile DWC_MSH8_REGMODEL_CMDPAD_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_cmdpad_cnfg_phy;    // 0x304
    volatile DWC_MSH8_REGMODEL_DATPAD_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_datpad_cnfg_phy;    // 0x306
    volatile DWC_MSH8_REGMODEL_CLKPAD_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_clkpad_cnfg_phy;    // 0x308
    volatile DWC_MSH8_REGMODEL_STBPAD_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_stbpad_cnfg_phy;    // 0x30a
    volatile DWC_MSH8_REGMODEL_RSTNPAD_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_rstnpad_cnfg_phy;    // 0x30c
    volatile DWC_MSH8_REGMODEL_PADTEST_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_padtest_cnfg_phy;    // 0x30e
    volatile DWC_MSH8_REGMODEL_PADTEST_OUT_PHY_BLOCK_U dwc_msh8_regmodel_padtest_out_phy;    // 0x310
    volatile DWC_MSH8_REGMODEL_PADTEST_IN_PHY_BLOCK_U dwc_msh8_regmodel_padtest_in_phy;    // 0x312
    volatile DWC_MSH8_REGMODEL_PRBS_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_prbs_cnfg_phy;    // 0x318
    volatile DWC_MSH8_REGMODEL_PHYLPBK_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_phylpbk_cnfg_phy;    // 0x31a
    volatile DWC_MSH8_REGMODEL_COMMDL_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_commdl_cnfg_phy;    // 0x31c
    volatile DWC_MSH8_REGMODEL_SDCLKDL_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_sdclkdl_cnfg_phy;    // 0x31d
    volatile DWC_MSH8_REGMODEL_SDCLKDL_DC_PHY_BLOCK_U dwc_msh8_regmodel_sdclkdl_dc_phy;    // 0x31e
    volatile DWC_MSH8_REGMODEL_SMPLDL_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_smpldl_cnfg_phy;    // 0x320
    volatile DWC_MSH8_REGMODEL_ATDL_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_atdl_cnfg_phy;    // 0x321
    volatile DWC_MSH8_REGMODEL_DLL_CTRL_PHY_BLOCK_U dwc_msh8_regmodel_dll_ctrl_phy;    // 0x324
    volatile DWC_MSH8_REGMODEL_DLL_CNFG1_PHY_BLOCK_U dwc_msh8_regmodel_dll_cnfg1_phy;    // 0x325
    volatile DWC_MSH8_REGMODEL_DLL_CNFG2_PHY_BLOCK_U dwc_msh8_regmodel_dll_cnfg2_phy;    // 0x326
    volatile DWC_MSH8_REGMODEL_DLLDL_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_dlldl_cnfg_phy;    // 0x328
    volatile DWC_MSH8_REGMODEL_DLL_OFFST_PHY_BLOCK_U dwc_msh8_regmodel_dll_offst_phy;    // 0x329
    volatile DWC_MSH8_REGMODEL_DLLMST_TSTDC_PHY_BLOCK_U dwc_msh8_regmodel_dllmst_tstdc_phy;    // 0x32a
    volatile DWC_MSH8_REGMODEL_DLLLBT_CNFG_PHY_BLOCK_U dwc_msh8_regmodel_dlllbt_cnfg_phy;    // 0x32c
    volatile DWC_MSH8_REGMODEL_DLL_STATUS_PHY_BLOCK_U dwc_msh8_regmodel_dll_status_phy;    // 0x32e
    volatile DWC_MSH8_REGMODEL_DLLDBG_MLKDC_PHY_BLOCK_U dwc_msh8_regmodel_dlldbg_mlkdc_phy;    // 0x330
    volatile DWC_MSH8_REGMODEL_DLLDBG_SLKDC_PHY_BLOCK_U dwc_msh8_regmodel_dlldbg_slkdc_phy;    // 0x332
} DWC_MSH8_REGMODEL_REG_S;

#endif

